// Generated by CIRCT unknown git version
// Standard header to adapt well known macros to our needs.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

module TLB_1(
  input         clock,
                reset,
                io_req_valid,
  input  [39:0] io_req_bits_vaddr,
  input         io_req_bits_passthrough,
  input  [2:0]  io_req_bits_size,
  input  [4:0]  io_req_bits_cmd,
  input  [1:0]  io_req_bits_prv,
  input         io_sfence_valid,
                io_ptw_req_ready,
                io_ptw_resp_valid,
                io_ptw_resp_bits_ae_ptw,
                io_ptw_resp_bits_ae_final,
                io_ptw_resp_bits_pf,
                io_ptw_resp_bits_gf,
                io_ptw_resp_bits_hr,
                io_ptw_resp_bits_hw,
                io_ptw_resp_bits_hx,
  input  [43:0] io_ptw_resp_bits_pte_ppn,
  input         io_ptw_resp_bits_pte_d,
                io_ptw_resp_bits_pte_a,
                io_ptw_resp_bits_pte_g,
                io_ptw_resp_bits_pte_u,
                io_ptw_resp_bits_pte_x,
                io_ptw_resp_bits_pte_w,
                io_ptw_resp_bits_pte_r,
                io_ptw_resp_bits_pte_v,
  input  [1:0]  io_ptw_resp_bits_level,
  input         io_ptw_resp_bits_homogeneous,
  input  [3:0]  io_ptw_ptbr_mode,
  input         io_ptw_status_debug,
                io_ptw_status_mxr,
                io_ptw_status_sum,
                io_ptw_pmp_0_cfg_l,
  input  [1:0]  io_ptw_pmp_0_cfg_a,
  input         io_ptw_pmp_0_cfg_x,
                io_ptw_pmp_0_cfg_w,
                io_ptw_pmp_0_cfg_r,
  input  [29:0] io_ptw_pmp_0_addr,
  input  [31:0] io_ptw_pmp_0_mask,
  input         io_ptw_pmp_1_cfg_l,
  input  [1:0]  io_ptw_pmp_1_cfg_a,
  input         io_ptw_pmp_1_cfg_x,
                io_ptw_pmp_1_cfg_w,
                io_ptw_pmp_1_cfg_r,
  input  [29:0] io_ptw_pmp_1_addr,
  input  [31:0] io_ptw_pmp_1_mask,
  input         io_ptw_pmp_2_cfg_l,
  input  [1:0]  io_ptw_pmp_2_cfg_a,
  input         io_ptw_pmp_2_cfg_x,
                io_ptw_pmp_2_cfg_w,
                io_ptw_pmp_2_cfg_r,
  input  [29:0] io_ptw_pmp_2_addr,
  input  [31:0] io_ptw_pmp_2_mask,
  input         io_ptw_pmp_3_cfg_l,
  input  [1:0]  io_ptw_pmp_3_cfg_a,
  input         io_ptw_pmp_3_cfg_x,
                io_ptw_pmp_3_cfg_w,
                io_ptw_pmp_3_cfg_r,
  input  [29:0] io_ptw_pmp_3_addr,
  input  [31:0] io_ptw_pmp_3_mask,
  input         io_ptw_pmp_4_cfg_l,
  input  [1:0]  io_ptw_pmp_4_cfg_a,
  input         io_ptw_pmp_4_cfg_x,
                io_ptw_pmp_4_cfg_w,
                io_ptw_pmp_4_cfg_r,
  input  [29:0] io_ptw_pmp_4_addr,
  input  [31:0] io_ptw_pmp_4_mask,
  input         io_ptw_pmp_5_cfg_l,
  input  [1:0]  io_ptw_pmp_5_cfg_a,
  input         io_ptw_pmp_5_cfg_x,
                io_ptw_pmp_5_cfg_w,
                io_ptw_pmp_5_cfg_r,
  input  [29:0] io_ptw_pmp_5_addr,
  input  [31:0] io_ptw_pmp_5_mask,
  input         io_ptw_pmp_6_cfg_l,
  input  [1:0]  io_ptw_pmp_6_cfg_a,
  input         io_ptw_pmp_6_cfg_x,
                io_ptw_pmp_6_cfg_w,
                io_ptw_pmp_6_cfg_r,
  input  [29:0] io_ptw_pmp_6_addr,
  input  [31:0] io_ptw_pmp_6_mask,
  input         io_ptw_pmp_7_cfg_l,
  input  [1:0]  io_ptw_pmp_7_cfg_a,
  input         io_ptw_pmp_7_cfg_x,
                io_ptw_pmp_7_cfg_w,
                io_ptw_pmp_7_cfg_r,
  input  [29:0] io_ptw_pmp_7_addr,
  input  [31:0] io_ptw_pmp_7_mask,
  output        io_resp_miss,
  output [31:0] io_resp_paddr,
  output        io_resp_pf_ld,
                io_resp_pf_st,
                io_resp_ae_ld,
                io_resp_ae_st,
                io_ptw_req_valid,
  output [26:0] io_ptw_req_bits_bits_addr,
  output        io_ptw_req_bits_bits_need_gpa,
                io_ptw_req_bits_bits_vstage1,
                io_ptw_req_bits_bits_stage2
);

  wire [19:0]      _entries_barrier_5_io_y_ppn;	// @[package.scala:259:25]
  wire             _entries_barrier_5_io_y_u;	// @[package.scala:259:25]
  wire             _entries_barrier_5_io_y_ae_ptw;	// @[package.scala:259:25]
  wire             _entries_barrier_5_io_y_ae_final;	// @[package.scala:259:25]
  wire             _entries_barrier_5_io_y_pf;	// @[package.scala:259:25]
  wire             _entries_barrier_5_io_y_gf;	// @[package.scala:259:25]
  wire             _entries_barrier_5_io_y_sw;	// @[package.scala:259:25]
  wire             _entries_barrier_5_io_y_sx;	// @[package.scala:259:25]
  wire             _entries_barrier_5_io_y_sr;	// @[package.scala:259:25]
  wire             _entries_barrier_5_io_y_pw;	// @[package.scala:259:25]
  wire             _entries_barrier_5_io_y_px;	// @[package.scala:259:25]
  wire             _entries_barrier_5_io_y_pr;	// @[package.scala:259:25]
  wire             _entries_barrier_5_io_y_ppp;	// @[package.scala:259:25]
  wire             _entries_barrier_5_io_y_pal;	// @[package.scala:259:25]
  wire             _entries_barrier_5_io_y_paa;	// @[package.scala:259:25]
  wire             _entries_barrier_5_io_y_eff;	// @[package.scala:259:25]
  wire             _entries_barrier_5_io_y_c;	// @[package.scala:259:25]
  wire [19:0]      _entries_barrier_4_io_y_ppn;	// @[package.scala:259:25]
  wire             _entries_barrier_4_io_y_u;	// @[package.scala:259:25]
  wire             _entries_barrier_4_io_y_ae_ptw;	// @[package.scala:259:25]
  wire             _entries_barrier_4_io_y_ae_final;	// @[package.scala:259:25]
  wire             _entries_barrier_4_io_y_pf;	// @[package.scala:259:25]
  wire             _entries_barrier_4_io_y_gf;	// @[package.scala:259:25]
  wire             _entries_barrier_4_io_y_sw;	// @[package.scala:259:25]
  wire             _entries_barrier_4_io_y_sx;	// @[package.scala:259:25]
  wire             _entries_barrier_4_io_y_sr;	// @[package.scala:259:25]
  wire             _entries_barrier_4_io_y_pw;	// @[package.scala:259:25]
  wire             _entries_barrier_4_io_y_px;	// @[package.scala:259:25]
  wire             _entries_barrier_4_io_y_pr;	// @[package.scala:259:25]
  wire             _entries_barrier_4_io_y_ppp;	// @[package.scala:259:25]
  wire             _entries_barrier_4_io_y_pal;	// @[package.scala:259:25]
  wire             _entries_barrier_4_io_y_paa;	// @[package.scala:259:25]
  wire             _entries_barrier_4_io_y_eff;	// @[package.scala:259:25]
  wire             _entries_barrier_4_io_y_c;	// @[package.scala:259:25]
  wire [19:0]      _entries_barrier_3_io_y_ppn;	// @[package.scala:259:25]
  wire             _entries_barrier_3_io_y_u;	// @[package.scala:259:25]
  wire             _entries_barrier_3_io_y_ae_ptw;	// @[package.scala:259:25]
  wire             _entries_barrier_3_io_y_ae_final;	// @[package.scala:259:25]
  wire             _entries_barrier_3_io_y_pf;	// @[package.scala:259:25]
  wire             _entries_barrier_3_io_y_gf;	// @[package.scala:259:25]
  wire             _entries_barrier_3_io_y_sw;	// @[package.scala:259:25]
  wire             _entries_barrier_3_io_y_sx;	// @[package.scala:259:25]
  wire             _entries_barrier_3_io_y_sr;	// @[package.scala:259:25]
  wire             _entries_barrier_3_io_y_pw;	// @[package.scala:259:25]
  wire             _entries_barrier_3_io_y_px;	// @[package.scala:259:25]
  wire             _entries_barrier_3_io_y_pr;	// @[package.scala:259:25]
  wire             _entries_barrier_3_io_y_ppp;	// @[package.scala:259:25]
  wire             _entries_barrier_3_io_y_pal;	// @[package.scala:259:25]
  wire             _entries_barrier_3_io_y_paa;	// @[package.scala:259:25]
  wire             _entries_barrier_3_io_y_eff;	// @[package.scala:259:25]
  wire             _entries_barrier_3_io_y_c;	// @[package.scala:259:25]
  wire [19:0]      _entries_barrier_2_io_y_ppn;	// @[package.scala:259:25]
  wire             _entries_barrier_2_io_y_u;	// @[package.scala:259:25]
  wire             _entries_barrier_2_io_y_ae_ptw;	// @[package.scala:259:25]
  wire             _entries_barrier_2_io_y_ae_final;	// @[package.scala:259:25]
  wire             _entries_barrier_2_io_y_pf;	// @[package.scala:259:25]
  wire             _entries_barrier_2_io_y_gf;	// @[package.scala:259:25]
  wire             _entries_barrier_2_io_y_sw;	// @[package.scala:259:25]
  wire             _entries_barrier_2_io_y_sx;	// @[package.scala:259:25]
  wire             _entries_barrier_2_io_y_sr;	// @[package.scala:259:25]
  wire             _entries_barrier_2_io_y_pw;	// @[package.scala:259:25]
  wire             _entries_barrier_2_io_y_px;	// @[package.scala:259:25]
  wire             _entries_barrier_2_io_y_pr;	// @[package.scala:259:25]
  wire             _entries_barrier_2_io_y_ppp;	// @[package.scala:259:25]
  wire             _entries_barrier_2_io_y_pal;	// @[package.scala:259:25]
  wire             _entries_barrier_2_io_y_paa;	// @[package.scala:259:25]
  wire             _entries_barrier_2_io_y_eff;	// @[package.scala:259:25]
  wire             _entries_barrier_2_io_y_c;	// @[package.scala:259:25]
  wire [19:0]      _entries_barrier_1_io_y_ppn;	// @[package.scala:259:25]
  wire             _entries_barrier_1_io_y_u;	// @[package.scala:259:25]
  wire             _entries_barrier_1_io_y_ae_ptw;	// @[package.scala:259:25]
  wire             _entries_barrier_1_io_y_ae_final;	// @[package.scala:259:25]
  wire             _entries_barrier_1_io_y_pf;	// @[package.scala:259:25]
  wire             _entries_barrier_1_io_y_gf;	// @[package.scala:259:25]
  wire             _entries_barrier_1_io_y_sw;	// @[package.scala:259:25]
  wire             _entries_barrier_1_io_y_sx;	// @[package.scala:259:25]
  wire             _entries_barrier_1_io_y_sr;	// @[package.scala:259:25]
  wire             _entries_barrier_1_io_y_pw;	// @[package.scala:259:25]
  wire             _entries_barrier_1_io_y_px;	// @[package.scala:259:25]
  wire             _entries_barrier_1_io_y_pr;	// @[package.scala:259:25]
  wire             _entries_barrier_1_io_y_ppp;	// @[package.scala:259:25]
  wire             _entries_barrier_1_io_y_pal;	// @[package.scala:259:25]
  wire             _entries_barrier_1_io_y_paa;	// @[package.scala:259:25]
  wire             _entries_barrier_1_io_y_eff;	// @[package.scala:259:25]
  wire             _entries_barrier_1_io_y_c;	// @[package.scala:259:25]
  wire [19:0]      _entries_barrier_io_y_ppn;	// @[package.scala:259:25]
  wire             _entries_barrier_io_y_u;	// @[package.scala:259:25]
  wire             _entries_barrier_io_y_ae_ptw;	// @[package.scala:259:25]
  wire             _entries_barrier_io_y_ae_final;	// @[package.scala:259:25]
  wire             _entries_barrier_io_y_pf;	// @[package.scala:259:25]
  wire             _entries_barrier_io_y_gf;	// @[package.scala:259:25]
  wire             _entries_barrier_io_y_sw;	// @[package.scala:259:25]
  wire             _entries_barrier_io_y_sx;	// @[package.scala:259:25]
  wire             _entries_barrier_io_y_sr;	// @[package.scala:259:25]
  wire             _entries_barrier_io_y_pw;	// @[package.scala:259:25]
  wire             _entries_barrier_io_y_px;	// @[package.scala:259:25]
  wire             _entries_barrier_io_y_pr;	// @[package.scala:259:25]
  wire             _entries_barrier_io_y_ppp;	// @[package.scala:259:25]
  wire             _entries_barrier_io_y_pal;	// @[package.scala:259:25]
  wire             _entries_barrier_io_y_paa;	// @[package.scala:259:25]
  wire             _entries_barrier_io_y_eff;	// @[package.scala:259:25]
  wire             _entries_barrier_io_y_c;	// @[package.scala:259:25]
  wire             _pmp_io_r;	// @[TLB.scala:405:19]
  wire             _pmp_io_w;	// @[TLB.scala:405:19]
  wire             _pmp_io_x;	// @[TLB.scala:405:19]
  wire [19:0]      _mpu_ppn_barrier_io_y_ppn;	// @[package.scala:259:25]
  wire             _mpu_ppn_barrier_io_y_u;	// @[package.scala:259:25]
  wire             _mpu_ppn_barrier_io_y_ae_ptw;	// @[package.scala:259:25]
  wire             _mpu_ppn_barrier_io_y_ae_final;	// @[package.scala:259:25]
  wire             _mpu_ppn_barrier_io_y_pf;	// @[package.scala:259:25]
  wire             _mpu_ppn_barrier_io_y_gf;	// @[package.scala:259:25]
  wire             _mpu_ppn_barrier_io_y_sw;	// @[package.scala:259:25]
  wire             _mpu_ppn_barrier_io_y_sx;	// @[package.scala:259:25]
  wire             _mpu_ppn_barrier_io_y_sr;	// @[package.scala:259:25]
  wire             _mpu_ppn_barrier_io_y_pw;	// @[package.scala:259:25]
  wire             _mpu_ppn_barrier_io_y_px;	// @[package.scala:259:25]
  wire             _mpu_ppn_barrier_io_y_pr;	// @[package.scala:259:25]
  wire             _mpu_ppn_barrier_io_y_ppp;	// @[package.scala:259:25]
  wire             _mpu_ppn_barrier_io_y_pal;	// @[package.scala:259:25]
  wire             _mpu_ppn_barrier_io_y_paa;	// @[package.scala:259:25]
  wire             _mpu_ppn_barrier_io_y_eff;	// @[package.scala:259:25]
  wire             _mpu_ppn_barrier_io_y_c;	// @[package.scala:259:25]
  reg  [26:0]      sectored_entries_0_0_tag_vpn;	// @[TLB.scala:328:29]
  reg              sectored_entries_0_0_tag_v;	// @[TLB.scala:328:29]
  reg  [40:0]      sectored_entries_0_0_data_0;	// @[TLB.scala:328:29]
  reg  [40:0]      sectored_entries_0_0_data_1;	// @[TLB.scala:328:29]
  reg  [40:0]      sectored_entries_0_0_data_2;	// @[TLB.scala:328:29]
  reg  [40:0]      sectored_entries_0_0_data_3;	// @[TLB.scala:328:29]
  reg              sectored_entries_0_0_valid_0;	// @[TLB.scala:328:29]
  reg              sectored_entries_0_0_valid_1;	// @[TLB.scala:328:29]
  reg              sectored_entries_0_0_valid_2;	// @[TLB.scala:328:29]
  reg              sectored_entries_0_0_valid_3;	// @[TLB.scala:328:29]
  reg  [1:0]       superpage_entries_0_level;	// @[TLB.scala:330:30]
  reg  [26:0]      superpage_entries_0_tag_vpn;	// @[TLB.scala:330:30]
  reg              superpage_entries_0_tag_v;	// @[TLB.scala:330:30]
  reg  [40:0]      superpage_entries_0_data_0;	// @[TLB.scala:330:30]
  reg              superpage_entries_0_valid_0;	// @[TLB.scala:330:30]
  reg  [1:0]       superpage_entries_1_level;	// @[TLB.scala:330:30]
  reg  [26:0]      superpage_entries_1_tag_vpn;	// @[TLB.scala:330:30]
  reg              superpage_entries_1_tag_v;	// @[TLB.scala:330:30]
  reg  [40:0]      superpage_entries_1_data_0;	// @[TLB.scala:330:30]
  reg              superpage_entries_1_valid_0;	// @[TLB.scala:330:30]
  reg  [1:0]       superpage_entries_2_level;	// @[TLB.scala:330:30]
  reg  [26:0]      superpage_entries_2_tag_vpn;	// @[TLB.scala:330:30]
  reg              superpage_entries_2_tag_v;	// @[TLB.scala:330:30]
  reg  [40:0]      superpage_entries_2_data_0;	// @[TLB.scala:330:30]
  reg              superpage_entries_2_valid_0;	// @[TLB.scala:330:30]
  reg  [1:0]       superpage_entries_3_level;	// @[TLB.scala:330:30]
  reg  [26:0]      superpage_entries_3_tag_vpn;	// @[TLB.scala:330:30]
  reg              superpage_entries_3_tag_v;	// @[TLB.scala:330:30]
  reg  [40:0]      superpage_entries_3_data_0;	// @[TLB.scala:330:30]
  reg              superpage_entries_3_valid_0;	// @[TLB.scala:330:30]
  reg  [1:0]       special_entry_level;	// @[TLB.scala:335:56]
  reg  [26:0]      special_entry_tag_vpn;	// @[TLB.scala:335:56]
  reg              special_entry_tag_v;	// @[TLB.scala:335:56]
  reg  [40:0]      special_entry_data_0;	// @[TLB.scala:335:56]
  reg              special_entry_valid_0;	// @[TLB.scala:335:56]
  reg  [1:0]       state;	// @[TLB.scala:341:22]
  reg  [26:0]      r_refill_tag;	// @[TLB.scala:343:25]
  reg  [1:0]       r_superpage_repl_addr;	// @[TLB.scala:344:34]
  reg              r_sectored_hit_valid;	// @[TLB.scala:346:27]
  reg              r_vstage1_en;	// @[TLB.scala:348:25]
  reg              r_stage2_en;	// @[TLB.scala:349:24]
  reg              r_need_gpa;	// @[TLB.scala:350:23]
  wire             vm_enabled = io_ptw_ptbr_mode[3] & ~(io_req_bits_prv[1]) & ~io_req_bits_passthrough;	// @[TLB.scala:361:27, :363:41, :388:{61,64}]
  wire             _T_22 = state == 2'h1;	// @[TLB.scala:341:22, package.scala:16:47]
  wire             mpu_ppn_ignore = special_entry_level == 2'h0;	// @[TLB.scala:187:28, :335:56]
  wire [8:0]       _GEN = mpu_ppn_ignore ? io_req_bits_vaddr[29:21] : 9'h0;	// @[TLB.scala:173:79, :187:28, :188:28, :324:30]
  wire [8:0]       _GEN_0 = special_entry_level[1] ? 9'h0 : io_req_bits_vaddr[20:12];	// @[TLB.scala:173:79, :187:28, :188:28, :324:30, :335:56]
  wire [27:0]      mpu_ppn = io_ptw_resp_valid ? {8'h0, io_ptw_resp_bits_pte_ppn[19:0]} : vm_enabled ? {8'h0, _mpu_ppn_barrier_io_y_ppn[19:18], _GEN | _mpu_ppn_barrier_io_y_ppn[17:9], _GEN_0 | _mpu_ppn_barrier_io_y_ppn[8:0]} : io_req_bits_vaddr[39:12];	// @[TLB.scala:185:26, :188:{28,47}, :388:61, :395:44, :401:20, :402:{20,146}, package.scala:259:25]
  wire [2:0]       mpu_priv = io_ptw_resp_valid | io_req_bits_passthrough ? 3'h1 : {io_ptw_status_debug, io_req_bits_prv};	// @[Cat.scala:33:92, TLB.scala:404:{27,52}]
  wire [10:0]      _GEN_1 = mpu_ppn[14:4] ^ 11'h201;	// @[Parameters.scala:137:31, TLB.scala:401:20]
  wire [1:0]       _GEN_2 = mpu_ppn[14:13] ^ 2'h1;	// @[Cat.scala:33:92, Parameters.scala:137:31, TLB.scala:401:20, package.scala:16:47]
  wire [1:0]       _GEN_3 = mpu_ppn[5:4] ^ 2'h2;	// @[Cat.scala:33:92, Parameters.scala:137:31, TLB.scala:187:28, :401:20]
  wire             legal_address = mpu_ppn == 28'h3 | mpu_ppn == 28'h2010 | mpu_ppn == 28'h4 | mpu_ppn == 28'h54000 | mpu_ppn[27:14] == 14'h3 | mpu_ppn[27:4] == 24'h200 | mpu_ppn == 28'h0 | mpu_ppn[27:4] == 24'h1 | mpu_ppn == 28'h100 | mpu_ppn == 28'h110 | mpu_ppn[27:16] == 12'h8 | mpu_ppn == 28'h10000 | mpu_ppn[27:4] == 24'h2;	// @[Cat.scala:33:92, Parameters.scala:137:{31,65}, TLB.scala:401:20, :412:67]
  wire [3:0]       _GEN_4 = mpu_ppn[16:13] ^ 4'hA;	// @[Cat.scala:33:92, Parameters.scala:137:31, TLB.scala:401:20]
  wire [1:0]       _GEN_5 = {~(mpu_ppn[19]), mpu_ppn[16]};	// @[Cat.scala:33:92, Parameters.scala:137:{31,45}, TLB.scala:401:20]
  wire             newEntry_c = legal_address & ({mpu_ppn[19], mpu_ppn[16], mpu_ppn[14], _GEN_3} == 5'h0 | {mpu_ppn[19], ~(mpu_ppn[16]), mpu_ppn[14], mpu_ppn[5:4]} == 5'h0 | _GEN_5 == 2'h0);	// @[Cat.scala:33:92, OneHot.scala:57:35, Parameters.scala:137:{31,45,65}, :615:89, TLB.scala:401:20, :412:67, :415:19]
  wire             deny_access_to_debug = ~(mpu_priv[2]) & mpu_ppn == 28'h0;	// @[Parameters.scala:137:65, TLB.scala:401:20, :404:27, :420:{39,50}]
  wire             newEntry_pr = legal_address & ~deny_access_to_debug & _pmp_io_r;	// @[TLB.scala:405:19, :412:67, :420:50, :421:{44,66}]
  wire [5:0]       _GEN_6 = {mpu_ppn[19], mpu_ppn[15], mpu_ppn[13], mpu_ppn[8], mpu_ppn[5:4]};	// @[Cat.scala:33:92, Parameters.scala:137:45, TLB.scala:401:20]
  wire [5:0]       _GEN_7 = {mpu_ppn[19], mpu_ppn[16:15], mpu_ppn[13], ~(mpu_ppn[8]), mpu_ppn[5]};	// @[Cat.scala:33:92, Parameters.scala:137:{31,45}, TLB.scala:401:20]
  wire [5:0]       _GEN_8 = {mpu_ppn[19], mpu_ppn[16:15], _GEN_2[0], mpu_ppn[8], mpu_ppn[5]};	// @[Cat.scala:33:92, Parameters.scala:137:{31,45}, TLB.scala:401:20]
  wire [2:0]       _GEN_9 = {mpu_ppn[19], mpu_ppn[16:15] ^ 2'h1};	// @[Cat.scala:33:92, Parameters.scala:137:{31,45}, TLB.scala:401:20, package.scala:16:47]
  wire             newEntry_pw = legal_address & (_GEN_6 == 6'h0 | _GEN_7 == 6'h0 | _GEN_8 == 6'h0 | _GEN_9 == 3'h0 | _GEN_5 == 2'h0) & ~deny_access_to_debug & _pmp_io_w;	// @[Bitwise.scala:77:12, Parameters.scala:137:{45,65}, :615:89, Replacement.scala:168:70, TLB.scala:405:19, :412:67, :420:50, :421:44, :422:70]
  wire             newEntry_ppp = legal_address & (_GEN_6 == 6'h0 | _GEN_7 == 6'h0 | _GEN_8 == 6'h0 | _GEN_9 == 3'h0 | _GEN_5 == 2'h0);	// @[Bitwise.scala:77:12, Parameters.scala:137:{45,65}, :615:89, Replacement.scala:168:70, TLB.scala:412:67, :415:19]
  wire             newEntry_pal = legal_address & (_GEN_6 == 6'h0 | _GEN_7 == 6'h0 | _GEN_8 == 6'h0 | _GEN_9 == 3'h0 | _GEN_5 == 2'h0);	// @[Bitwise.scala:77:12, Parameters.scala:137:{45,65}, :615:89, Replacement.scala:168:70, TLB.scala:412:67, :415:19]
  wire             newEntry_paa = legal_address & (_GEN_6 == 6'h0 | _GEN_7 == 6'h0 | _GEN_8 == 6'h0 | _GEN_9 == 3'h0 | _GEN_5 == 2'h0);	// @[Bitwise.scala:77:12, Parameters.scala:137:{45,65}, :615:89, Replacement.scala:168:70, TLB.scala:412:67, :415:19]
  wire             newEntry_eff = legal_address & ({mpu_ppn[19], mpu_ppn[16], mpu_ppn[14:13], mpu_ppn[8], mpu_ppn[5:4], mpu_ppn[1]} == 8'h0 | {mpu_ppn[19], mpu_ppn[16], mpu_ppn[14:13], ~(mpu_ppn[8]), mpu_ppn[5], mpu_ppn[1]} == 7'h0 | {mpu_ppn[19], mpu_ppn[16], _GEN_2, mpu_ppn[8], mpu_ppn[5:4]} == 7'h0 | {mpu_ppn[19], mpu_ppn[16], _GEN_1[10:9], mpu_ppn[8], _GEN_1[1:0], mpu_ppn[1]} == 8'h0 | {mpu_ppn[19], mpu_ppn[16], ~(mpu_ppn[14])} == 3'h0 | {mpu_ppn[19], _GEN_4[3], _GEN_4[1:0], mpu_ppn[8], mpu_ppn[5:4], mpu_ppn[1]} == 8'h0);	// @[Cat.scala:33:92, Parameters.scala:137:{31,45,65}, :615:89, Replacement.scala:168:70, TLB.scala:401:20, :402:20, :412:67, :415:19, :587:19]
  wire [24:0]      _sector_hits_T_4 = sectored_entries_0_0_tag_vpn[26:2] ^ io_req_bits_vaddr[38:14];	// @[TLB.scala:164:61, :324:30, :328:29]
  wire [17:0]      _GEN_10 = superpage_entries_0_tag_vpn[26:9] ^ io_req_bits_vaddr[38:21];	// @[TLB.scala:173:52, :324:30, :330:30]
  wire             superpage_hits_ignore_1 = superpage_entries_0_level == 2'h0;	// @[TLB.scala:172:28, :330:30]
  wire [17:0]      _GEN_11 = superpage_entries_1_tag_vpn[26:9] ^ io_req_bits_vaddr[38:21];	// @[TLB.scala:173:52, :324:30, :330:30]
  wire             superpage_hits_ignore_4 = superpage_entries_1_level == 2'h0;	// @[TLB.scala:172:28, :330:30]
  wire [17:0]      _GEN_12 = superpage_entries_2_tag_vpn[26:9] ^ io_req_bits_vaddr[38:21];	// @[TLB.scala:173:52, :324:30, :330:30]
  wire             superpage_hits_ignore_7 = superpage_entries_2_level == 2'h0;	// @[TLB.scala:172:28, :330:30]
  wire [17:0]      _GEN_13 = superpage_entries_3_tag_vpn[26:9] ^ io_req_bits_vaddr[38:21];	// @[TLB.scala:173:52, :324:30, :330:30]
  wire             superpage_hits_ignore_10 = superpage_entries_3_level == 2'h0;	// @[TLB.scala:172:28, :330:30]
  wire [3:0]       _GEN_14 = {{sectored_entries_0_0_valid_3}, {sectored_entries_0_0_valid_2}, {sectored_entries_0_0_valid_1}, {sectored_entries_0_0_valid_0}};	// @[TLB.scala:178:18, :328:29]
  wire             hitsVec_0 = vm_enabled & _GEN_14[io_req_bits_vaddr[13:12]] & _sector_hits_T_4 == 25'h0 & ~sectored_entries_0_0_tag_v;	// @[TLB.scala:164:{61,86,105}, :178:18, :324:30, :328:29, :388:61, :432:44, package.scala:155:13]
  wire             hitsVec_1 = vm_enabled & superpage_entries_0_valid_0 & ~superpage_entries_0_tag_v & _GEN_10[17:9] == 9'h0 & (superpage_hits_ignore_1 | _GEN_10[8:0] == 9'h0);	// @[TLB.scala:168:43, :172:28, :173:{40,52,58,79}, :330:30, :388:61, :432:44]
  wire             hitsVec_2 = vm_enabled & superpage_entries_1_valid_0 & ~superpage_entries_1_tag_v & _GEN_11[17:9] == 9'h0 & (superpage_hits_ignore_4 | _GEN_11[8:0] == 9'h0);	// @[TLB.scala:168:43, :172:28, :173:{40,52,58,79}, :330:30, :388:61, :432:44]
  wire             hitsVec_3 = vm_enabled & superpage_entries_2_valid_0 & ~superpage_entries_2_tag_v & _GEN_12[17:9] == 9'h0 & (superpage_hits_ignore_7 | _GEN_12[8:0] == 9'h0);	// @[TLB.scala:168:43, :172:28, :173:{40,52,58,79}, :330:30, :388:61, :432:44]
  wire             hitsVec_4 = vm_enabled & superpage_entries_3_valid_0 & ~superpage_entries_3_tag_v & _GEN_13[17:9] == 9'h0 & (superpage_hits_ignore_10 | _GEN_13[8:0] == 9'h0);	// @[TLB.scala:168:43, :172:28, :173:{40,52,58,79}, :330:30, :388:61, :432:44]
  wire [26:0]      _T_721 = special_entry_tag_vpn ^ io_req_bits_vaddr[38:12];	// @[TLB.scala:173:52, :324:30, :335:56]
  wire             hitsVec_5 = vm_enabled & special_entry_valid_0 & ~special_entry_tag_v & _T_721[26:18] == 9'h0 & (mpu_ppn_ignore | _T_721[17:9] == 9'h0) & (~(special_entry_level[1]) | _T_721[8:0] == 9'h0);	// @[TLB.scala:168:43, :173:{40,52,58,79}, :187:28, :335:56, :388:61, :432:44]
  wire [5:0]       real_hits = {hitsVec_5, hitsVec_4, hitsVec_3, hitsVec_2, hitsVec_1, hitsVec_0};	// @[Cat.scala:33:92, TLB.scala:432:44]
  wire [6:0]       hits = {~vm_enabled, hitsVec_5, hitsVec_4, hitsVec_3, hitsVec_2, hitsVec_1, hitsVec_0};	// @[Cat.scala:33:92, TLB.scala:388:61, :432:44, :434:18]
  wire [3:0][40:0] _GEN_15 = {{sectored_entries_0_0_data_3}, {sectored_entries_0_0_data_2}, {sectored_entries_0_0_data_1}, {sectored_entries_0_0_data_0}};	// @[TLB.scala:160:77, :328:29]
  wire [40:0]      _entries_WIRE_1 = _GEN_15[io_req_bits_vaddr[13:12]];	// @[TLB.scala:160:77, :324:30, package.scala:155:13]
  wire [6:0]       ptw_pf_array = {1'h0, _entries_barrier_5_io_y_pf, _entries_barrier_4_io_y_pf, _entries_barrier_3_io_y_pf, _entries_barrier_2_io_y_pf, _entries_barrier_1_io_y_pf, _entries_barrier_io_y_pf};	// @[Cat.scala:33:92, package.scala:259:25]
  wire [5:0]       priv_rw_ok = (~(io_req_bits_prv[0]) | io_ptw_status_sum ? {_entries_barrier_5_io_y_u, _entries_barrier_4_io_y_u, _entries_barrier_3_io_y_u, _entries_barrier_2_io_y_u, _entries_barrier_1_io_y_u, _entries_barrier_io_y_u} : 6'h0) | (io_req_bits_prv[0] ? ~{_entries_barrier_5_io_y_u, _entries_barrier_4_io_y_u, _entries_barrier_3_io_y_u, _entries_barrier_2_io_y_u, _entries_barrier_1_io_y_u, _entries_barrier_io_y_u} : 6'h0);	// @[Bitwise.scala:77:12, Cat.scala:33:92, TLB.scala:359:20, :504:{23,24,32,70,75,84}, package.scala:259:25]
  wire             _GEN_16 = _entries_barrier_5_io_y_ae_ptw | _entries_barrier_5_io_y_ae_final;	// @[TLB.scala:520:104, package.scala:259:25]
  wire             _GEN_17 = _entries_barrier_4_io_y_ae_ptw | _entries_barrier_4_io_y_ae_final;	// @[TLB.scala:520:104, package.scala:259:25]
  wire             _GEN_18 = _entries_barrier_3_io_y_ae_ptw | _entries_barrier_3_io_y_ae_final;	// @[TLB.scala:520:104, package.scala:259:25]
  wire             _GEN_19 = _entries_barrier_2_io_y_ae_ptw | _entries_barrier_2_io_y_ae_final;	// @[TLB.scala:520:104, package.scala:259:25]
  wire             _GEN_20 = _entries_barrier_1_io_y_ae_ptw | _entries_barrier_1_io_y_ae_final;	// @[TLB.scala:520:104, package.scala:259:25]
  wire             _GEN_21 = _entries_barrier_io_y_ae_ptw | _entries_barrier_io_y_ae_final;	// @[TLB.scala:520:104, package.scala:259:25]
  wire [6:0]       c_array = {{2{newEntry_c}}, _entries_barrier_4_io_y_c, _entries_barrier_3_io_y_c, _entries_barrier_2_io_y_c, _entries_barrier_1_io_y_c, _entries_barrier_io_y_c};	// @[Bitwise.scala:77:12, Cat.scala:33:92, TLB.scala:415:19, package.scala:259:25]
  wire             bad_va = vm_enabled & io_ptw_ptbr_mode[3] & ~(io_req_bits_vaddr[39:38] == 2'h0 | (&(io_req_bits_vaddr[39:38])));	// @[TLB.scala:363:41, :388:61, :550:43, :551:{37,51,59,86}, :559:34]
  wire             _cmd_read_T_2 = io_req_bits_cmd == 5'h6;	// @[package.scala:16:47]
  wire             _cmd_write_T_3 = io_req_bits_cmd == 5'h7;	// @[package.scala:16:47]
  wire             _cmd_write_T_5 = io_req_bits_cmd == 5'h4;	// @[package.scala:16:47]
  wire             _cmd_write_T_6 = io_req_bits_cmd == 5'h9;	// @[package.scala:16:47]
  wire             _cmd_write_T_7 = io_req_bits_cmd == 5'hA;	// @[package.scala:16:47]
  wire             _cmd_write_T_8 = io_req_bits_cmd == 5'hB;	// @[package.scala:16:47]
  wire             _cmd_write_T_12 = io_req_bits_cmd == 5'h8;	// @[package.scala:16:47]
  wire             _cmd_write_T_13 = io_req_bits_cmd == 5'hC;	// @[package.scala:16:47]
  wire             _cmd_write_T_14 = io_req_bits_cmd == 5'hD;	// @[package.scala:16:47]
  wire             _cmd_write_T_15 = io_req_bits_cmd == 5'hE;	// @[package.scala:16:47]
  wire             _cmd_write_T_16 = io_req_bits_cmd == 5'hF;	// @[package.scala:16:47]
  wire             cmd_put_partial = io_req_bits_cmd == 5'h11;	// @[TLB.scala:564:41]
  wire             cmd_read = io_req_bits_cmd == 5'h0 | io_req_bits_cmd == 5'h10 | _cmd_read_T_2 | _cmd_write_T_3 | _cmd_write_T_5 | _cmd_write_T_6 | _cmd_write_T_7 | _cmd_write_T_8 | _cmd_write_T_12 | _cmd_write_T_13 | _cmd_write_T_14 | _cmd_write_T_15 | _cmd_write_T_16;	// @[Consts.scala:85:68, OneHot.scala:57:35, package.scala:16:47]
  wire             cmd_write_perms = io_req_bits_cmd == 5'h1 | cmd_put_partial | _cmd_write_T_3 | _cmd_write_T_5 | _cmd_write_T_6 | _cmd_write_T_7 | _cmd_write_T_8 | _cmd_write_T_12 | _cmd_write_T_13 | _cmd_write_T_14 | _cmd_write_T_15 | _cmd_write_T_16 | io_req_bits_cmd == 5'h5 | io_req_bits_cmd == 5'h17;	// @[Consts.scala:86:32, TLB.scala:564:41, :568:35, package.scala:16:47]
  wire [6:0]       ae_array = ((|(io_req_bits_vaddr[7:0] & (8'h1 << io_req_bits_size) - 8'h1)) ? {{2{newEntry_eff}}, _entries_barrier_4_io_y_eff, _entries_barrier_3_io_y_eff, _entries_barrier_2_io_y_eff, _entries_barrier_1_io_y_eff, _entries_barrier_io_y_eff} : 7'h0) | (_cmd_read_T_2 | _cmd_write_T_3 ? ~c_array : 7'h0);	// @[Bitwise.scala:77:12, Cat.scala:33:92, OneHot.scala:57:35, TLB.scala:415:19, :541:{39,69,77}, :573:{8,37}, :574:{8,19}, :587:19, package.scala:16:47, :73:59, :259:25]
  wire [6:0]       _gf_inst_array_T_1 = {1'h1, ~_entries_barrier_5_io_y_ae_ptw, ~_entries_barrier_4_io_y_ae_ptw, ~_entries_barrier_3_io_y_ae_ptw, ~_entries_barrier_2_io_y_ae_ptw, ~_entries_barrier_1_io_y_ae_ptw, ~_entries_barrier_io_y_ae_ptw};	// @[Cat.scala:33:92, TLB.scala:588:73, package.scala:259:25]
  wire [6:0]       _pf_inst_array_T_4 = {1'h1, ~_entries_barrier_5_io_y_gf, ~_entries_barrier_4_io_y_gf, ~_entries_barrier_3_io_y_gf, ~_entries_barrier_2_io_y_gf, ~_entries_barrier_1_io_y_gf, ~_entries_barrier_io_y_gf};	// @[Cat.scala:33:92, TLB.scala:588:106, package.scala:259:25]
  wire             tlb_miss = vm_enabled & ~bad_va & real_hits == 6'h0;	// @[Bitwise.scala:77:12, Cat.scala:33:92, TLB.scala:388:61, :559:34, :602:40, :604:{56,64}]
  reg  [2:0]       state_reg_1;	// @[Replacement.scala:168:70]
  wire             multipleHits_rightOne_1 = hitsVec_1 | hitsVec_2;	// @[Misc.scala:182:16, TLB.scala:432:44]
  wire             multipleHits_rightOne_3 = hitsVec_4 | hitsVec_5;	// @[Misc.scala:182:16, TLB.scala:432:44]
  wire             multipleHits = hitsVec_1 & hitsVec_2 | hitsVec_0 & multipleHits_rightOne_1 | hitsVec_4 & hitsVec_5 | hitsVec_3 & multipleHits_rightOne_3 | (hitsVec_0 | multipleHits_rightOne_1) & (hitsVec_3 | multipleHits_rightOne_3);	// @[Misc.scala:182:{16,49,61}, TLB.scala:432:44]
  wire [2:0]       _GEN_22 = ~{superpage_entries_2_valid_0, superpage_entries_1_valid_0, superpage_entries_0_valid_0};	// @[Cat.scala:33:92, TLB.scala:330:30, :746:43]
  wire             superpage_hits_1 = superpage_entries_1_valid_0 & ~superpage_entries_1_tag_v & _GEN_11[17:9] == 9'h0 & (superpage_hits_ignore_4 | _GEN_11[8:0] == 9'h0);	// @[TLB.scala:168:43, :172:28, :173:{29,40,52,58,79}, :330:30]
  wire             superpage_hits_2 = superpage_entries_2_valid_0 & ~superpage_entries_2_tag_v & _GEN_12[17:9] == 9'h0 & (superpage_hits_ignore_7 | _GEN_12[8:0] == 9'h0);	// @[TLB.scala:168:43, :172:28, :173:{29,40,52,58,79}, :330:30]
  wire             superpage_hits_3 = superpage_entries_3_valid_0 & ~superpage_entries_3_tag_v & _GEN_13[17:9] == 9'h0 & (superpage_hits_ignore_10 | _GEN_13[8:0] == 9'h0);	// @[TLB.scala:168:43, :172:28, :173:{29,40,52,58,79}, :330:30]
  wire [1:0]       hi_1 = {superpage_hits_3, superpage_hits_2};	// @[OneHot.scala:30:18, TLB.scala:173:29]
  wire             _T_16 = superpage_hits_3 | superpage_hits_1;	// @[OneHot.scala:32:28, TLB.scala:173:29]
  wire             invalidate_refill = _T_22 | (&state) | io_sfence_valid;	// @[TLB.scala:341:22, :399:88, package.scala:16:47]
  wire             newEntry_px = legal_address & ({mpu_ppn[19], mpu_ppn[14:13], mpu_ppn[8], mpu_ppn[5:4], mpu_ppn[2]} == 7'h0 | {mpu_ppn[19], mpu_ppn[16], mpu_ppn[14:13], mpu_ppn[8], mpu_ppn[5:4] ^ 2'h1} == 7'h0 | {mpu_ppn[19], mpu_ppn[16], mpu_ppn[14:13], mpu_ppn[8], _GEN_3} == 7'h0 | _GEN_5 == 2'h0) & ~deny_access_to_debug & _pmp_io_x;	// @[Cat.scala:33:92, Parameters.scala:137:{31,45,65}, :615:89, TLB.scala:401:20, :405:19, :412:67, :420:50, :421:44, :426:65, :587:19, package.scala:16:47]
  wire             refill_v = r_vstage1_en | r_stage2_en;	// @[TLB.scala:348:25, :349:24, :440:33]
  wire             newEntry_g = io_ptw_resp_bits_pte_g & io_ptw_resp_bits_pte_v;	// @[TLB.scala:445:25]
  wire             newEntry_sr = io_ptw_resp_bits_pte_v & (io_ptw_resp_bits_pte_r | io_ptw_resp_bits_pte_x & ~io_ptw_resp_bits_pte_w) & io_ptw_resp_bits_pte_a & io_ptw_resp_bits_pte_r;	// @[PTW.scala:141:{38,44,47}, :149:35]
  wire             newEntry_sw = io_ptw_resp_bits_pte_v & (io_ptw_resp_bits_pte_r | io_ptw_resp_bits_pte_x & ~io_ptw_resp_bits_pte_w) & io_ptw_resp_bits_pte_a & io_ptw_resp_bits_pte_w & io_ptw_resp_bits_pte_d;	// @[PTW.scala:141:{38,44,47}, :151:40]
  wire             newEntry_sx = io_ptw_resp_bits_pte_v & (io_ptw_resp_bits_pte_r | io_ptw_resp_bits_pte_x & ~io_ptw_resp_bits_pte_w) & io_ptw_resp_bits_pte_a & io_ptw_resp_bits_pte_x;	// @[PTW.scala:141:{38,44,47}, :153:35]
  wire             _GEN_23 = io_ptw_resp_valid & ~io_ptw_resp_bits_homogeneous;	// @[TLB.scala:201:18, :335:56, :438:20, :465:{39,70}]
  wire             _GEN_24 = io_ptw_resp_valid & io_ptw_resp_bits_homogeneous & ~(io_ptw_resp_bits_level[1]) & r_superpage_repl_addr == 2'h0;	// @[TLB.scala:330:30, :344:34, :438:20, :465:70, :467:40, :469:82]
  wire             _GEN_25 = io_ptw_resp_valid & io_ptw_resp_bits_homogeneous & ~(io_ptw_resp_bits_level[1]) & r_superpage_repl_addr == 2'h1;	// @[TLB.scala:330:30, :344:34, :438:20, :465:70, :467:40, :469:82, package.scala:16:47]
  wire             _GEN_26 = io_ptw_resp_valid & io_ptw_resp_bits_homogeneous & ~(io_ptw_resp_bits_level[1]) & r_superpage_repl_addr == 2'h2;	// @[TLB.scala:187:28, :330:30, :344:34, :438:20, :465:70, :467:40, :469:82]
  wire             _GEN_27 = io_ptw_resp_valid & io_ptw_resp_bits_homogeneous & ~(io_ptw_resp_bits_level[1]) & (&r_superpage_repl_addr);	// @[TLB.scala:330:30, :344:34, :438:20, :465:70, :467:40, :469:82]
  wire             _GEN_28 = ~io_ptw_resp_bits_homogeneous | ~(io_ptw_resp_bits_level[1]);	// @[TLB.scala:328:29, :465:{39,70}, :467:{40,58}, :477:84]
  wire             _GEN_29 = ~io_ptw_resp_valid | _GEN_28;	// @[TLB.scala:328:29, :438:20, :465:70, :467:58, :477:84]
  wire             _GEN_30 = r_refill_tag[1:0] == 2'h0;	// @[TLB.scala:206:16, :343:25, package.scala:155:13]
  wire             _GEN_31 = r_refill_tag[1:0] == 2'h1;	// @[TLB.scala:206:16, :343:25, package.scala:16:47, :155:13]
  wire             _GEN_32 = r_refill_tag[1:0] == 2'h2;	// @[TLB.scala:187:28, :206:16, :343:25, package.scala:155:13]
  wire [40:0]      _sectored_entries_0_0_data_T = {io_ptw_resp_bits_pte_ppn[19:0], io_ptw_resp_bits_pte_u, newEntry_g, io_ptw_resp_bits_ae_ptw, io_ptw_resp_bits_ae_final, io_ptw_resp_bits_pf, io_ptw_resp_bits_gf, newEntry_sw, newEntry_sx, newEntry_sr, io_ptw_resp_bits_hw, io_ptw_resp_bits_hx, io_ptw_resp_bits_hr, newEntry_pw, newEntry_px, newEntry_pr, newEntry_ppp, newEntry_pal, newEntry_paa, newEntry_eff, newEntry_c, 1'h0};	// @[PTW.scala:149:35, :151:40, :153:35, TLB.scala:207:24, :415:19, :421:66, :422:70, :426:65, :442:18, :445:25]
  wire             _T_21 = state == 2'h0 & io_req_valid & tlb_miss;	// @[TLB.scala:341:22, :604:64, :622:25, :668:23]
  wire             _T_987 = multipleHits | reset;	// @[Misc.scala:182:49, TLB.scala:721:24]
  wire             _GEN_33 = _T_987 | io_sfence_valid & ~sectored_entries_0_0_tag_v;	// @[TLB.scala:210:46, :213:{19,32,36}, :328:29, :438:20, :707:19, :712:42, :717:46, :721:{24,41}]
  always @(posedge clock) begin
    if (_GEN_29) begin	// @[TLB.scala:328:29, :438:20, :465:70]
    end
    else begin	// @[TLB.scala:328:29, :438:20, :465:70]
      sectored_entries_0_0_tag_vpn <= r_refill_tag;	// @[TLB.scala:328:29, :343:25]
      sectored_entries_0_0_tag_v <= refill_v;	// @[TLB.scala:328:29, :440:33]
    end
    if (~io_ptw_resp_valid | _GEN_28 | ~_GEN_30) begin	// @[TLB.scala:206:16, :328:29, :438:20, :465:70, :467:58, :477:84]
    end
    else	// @[TLB.scala:328:29, :438:20, :465:70]
      sectored_entries_0_0_data_0 <= _sectored_entries_0_0_data_T;	// @[TLB.scala:207:24, :328:29]
    if (~io_ptw_resp_valid | _GEN_28 | ~_GEN_31) begin	// @[TLB.scala:206:16, :328:29, :438:20, :465:70, :467:58, :477:84]
    end
    else	// @[TLB.scala:328:29, :438:20, :465:70]
      sectored_entries_0_0_data_1 <= _sectored_entries_0_0_data_T;	// @[TLB.scala:207:24, :328:29]
    if (~io_ptw_resp_valid | _GEN_28 | ~_GEN_32) begin	// @[TLB.scala:206:16, :328:29, :438:20, :465:70, :467:58, :477:84]
    end
    else	// @[TLB.scala:328:29, :438:20, :465:70]
      sectored_entries_0_0_data_2 <= _sectored_entries_0_0_data_T;	// @[TLB.scala:207:24, :328:29]
    if (~io_ptw_resp_valid | _GEN_28 | ~(&(r_refill_tag[1:0]))) begin	// @[TLB.scala:206:16, :328:29, :343:25, :438:20, :465:70, :467:58, :477:84, package.scala:155:13]
    end
    else	// @[TLB.scala:328:29, :438:20, :465:70]
      sectored_entries_0_0_data_3 <= _sectored_entries_0_0_data_T;	// @[TLB.scala:207:24, :328:29]
    sectored_entries_0_0_valid_0 <= ~_GEN_33 & (_GEN_29 ? sectored_entries_0_0_valid_0 : ~invalidate_refill & (_GEN_30 | r_sectored_hit_valid & sectored_entries_0_0_valid_0));	// @[TLB.scala:206:16, :210:46, :213:{32,36}, :328:29, :346:27, :399:88, :438:20, :465:70, :471:34, :478:38, :480:34, :707:19, :712:42, :717:46, :721:41]
    sectored_entries_0_0_valid_1 <= ~_GEN_33 & (_GEN_29 ? sectored_entries_0_0_valid_1 : ~invalidate_refill & (_GEN_31 | r_sectored_hit_valid & sectored_entries_0_0_valid_1));	// @[TLB.scala:206:16, :210:46, :213:{32,36}, :328:29, :346:27, :399:88, :438:20, :465:70, :471:34, :478:38, :480:34, :707:19, :712:42, :717:46, :721:41]
    sectored_entries_0_0_valid_2 <= ~_GEN_33 & (_GEN_29 ? sectored_entries_0_0_valid_2 : ~invalidate_refill & (_GEN_32 | r_sectored_hit_valid & sectored_entries_0_0_valid_2));	// @[TLB.scala:206:16, :210:46, :213:{32,36}, :328:29, :346:27, :399:88, :438:20, :465:70, :471:34, :478:38, :480:34, :707:19, :712:42, :717:46, :721:41]
    sectored_entries_0_0_valid_3 <= ~_GEN_33 & (_GEN_29 ? sectored_entries_0_0_valid_3 : ~invalidate_refill & ((&(r_refill_tag[1:0])) | r_sectored_hit_valid & sectored_entries_0_0_valid_3));	// @[TLB.scala:206:16, :210:46, :213:{32,36}, :328:29, :343:25, :346:27, :399:88, :438:20, :465:70, :471:34, :478:38, :480:34, :707:19, :712:42, :717:46, :721:41, package.scala:155:13]
    if (_GEN_24) begin	// @[TLB.scala:330:30, :438:20, :465:70]
      superpage_entries_0_level <= {1'h0, io_ptw_resp_bits_level[0]};	// @[TLB.scala:203:16, :330:30, package.scala:155:13]
      superpage_entries_0_tag_vpn <= r_refill_tag;	// @[TLB.scala:330:30, :343:25]
      superpage_entries_0_tag_v <= refill_v;	// @[TLB.scala:330:30, :440:33]
      superpage_entries_0_data_0 <= {io_ptw_resp_bits_pte_ppn[19:0], io_ptw_resp_bits_pte_u, newEntry_g, io_ptw_resp_bits_ae_ptw, io_ptw_resp_bits_ae_final, io_ptw_resp_bits_pf, io_ptw_resp_bits_gf, newEntry_sw, newEntry_sx, newEntry_sr, io_ptw_resp_bits_hw, io_ptw_resp_bits_hx, io_ptw_resp_bits_hr, newEntry_pw, newEntry_px, newEntry_pr, newEntry_ppp, newEntry_pal, newEntry_paa, newEntry_eff, newEntry_c, 1'h0};	// @[PTW.scala:149:35, :151:40, :153:35, TLB.scala:207:24, :330:30, :415:19, :421:66, :422:70, :426:65, :442:18, :445:25]
    end
    superpage_entries_0_valid_0 <= ~(_T_987 | io_sfence_valid & ~superpage_entries_0_tag_v) & (_GEN_24 ? ~invalidate_refill : superpage_entries_0_valid_0);	// @[TLB.scala:206:16, :210:46, :213:{19,32,36}, :330:30, :399:88, :438:20, :465:70, :471:34, :707:19, :712:42, :717:46, :721:{24,41}]
    if (_GEN_25) begin	// @[TLB.scala:330:30, :438:20, :465:70]
      superpage_entries_1_level <= {1'h0, io_ptw_resp_bits_level[0]};	// @[TLB.scala:203:16, :330:30, package.scala:155:13]
      superpage_entries_1_tag_vpn <= r_refill_tag;	// @[TLB.scala:330:30, :343:25]
      superpage_entries_1_tag_v <= refill_v;	// @[TLB.scala:330:30, :440:33]
      superpage_entries_1_data_0 <= {io_ptw_resp_bits_pte_ppn[19:0], io_ptw_resp_bits_pte_u, newEntry_g, io_ptw_resp_bits_ae_ptw, io_ptw_resp_bits_ae_final, io_ptw_resp_bits_pf, io_ptw_resp_bits_gf, newEntry_sw, newEntry_sx, newEntry_sr, io_ptw_resp_bits_hw, io_ptw_resp_bits_hx, io_ptw_resp_bits_hr, newEntry_pw, newEntry_px, newEntry_pr, newEntry_ppp, newEntry_pal, newEntry_paa, newEntry_eff, newEntry_c, 1'h0};	// @[PTW.scala:149:35, :151:40, :153:35, TLB.scala:207:24, :330:30, :415:19, :421:66, :422:70, :426:65, :442:18, :445:25]
    end
    superpage_entries_1_valid_0 <= ~(_T_987 | io_sfence_valid & ~superpage_entries_1_tag_v) & (_GEN_25 ? ~invalidate_refill : superpage_entries_1_valid_0);	// @[TLB.scala:206:16, :210:46, :213:{19,32,36}, :330:30, :399:88, :438:20, :465:70, :471:34, :707:19, :712:42, :717:46, :721:{24,41}]
    if (_GEN_26) begin	// @[TLB.scala:330:30, :438:20, :465:70]
      superpage_entries_2_level <= {1'h0, io_ptw_resp_bits_level[0]};	// @[TLB.scala:203:16, :330:30, package.scala:155:13]
      superpage_entries_2_tag_vpn <= r_refill_tag;	// @[TLB.scala:330:30, :343:25]
      superpage_entries_2_tag_v <= refill_v;	// @[TLB.scala:330:30, :440:33]
      superpage_entries_2_data_0 <= {io_ptw_resp_bits_pte_ppn[19:0], io_ptw_resp_bits_pte_u, newEntry_g, io_ptw_resp_bits_ae_ptw, io_ptw_resp_bits_ae_final, io_ptw_resp_bits_pf, io_ptw_resp_bits_gf, newEntry_sw, newEntry_sx, newEntry_sr, io_ptw_resp_bits_hw, io_ptw_resp_bits_hx, io_ptw_resp_bits_hr, newEntry_pw, newEntry_px, newEntry_pr, newEntry_ppp, newEntry_pal, newEntry_paa, newEntry_eff, newEntry_c, 1'h0};	// @[PTW.scala:149:35, :151:40, :153:35, TLB.scala:207:24, :330:30, :415:19, :421:66, :422:70, :426:65, :442:18, :445:25]
    end
    superpage_entries_2_valid_0 <= ~(_T_987 | io_sfence_valid & ~superpage_entries_2_tag_v) & (_GEN_26 ? ~invalidate_refill : superpage_entries_2_valid_0);	// @[TLB.scala:206:16, :210:46, :213:{19,32,36}, :330:30, :399:88, :438:20, :465:70, :471:34, :707:19, :712:42, :717:46, :721:{24,41}]
    if (_GEN_27) begin	// @[TLB.scala:330:30, :438:20, :465:70]
      superpage_entries_3_level <= {1'h0, io_ptw_resp_bits_level[0]};	// @[TLB.scala:203:16, :330:30, package.scala:155:13]
      superpage_entries_3_tag_vpn <= r_refill_tag;	// @[TLB.scala:330:30, :343:25]
      superpage_entries_3_tag_v <= refill_v;	// @[TLB.scala:330:30, :440:33]
      superpage_entries_3_data_0 <= {io_ptw_resp_bits_pte_ppn[19:0], io_ptw_resp_bits_pte_u, newEntry_g, io_ptw_resp_bits_ae_ptw, io_ptw_resp_bits_ae_final, io_ptw_resp_bits_pf, io_ptw_resp_bits_gf, newEntry_sw, newEntry_sx, newEntry_sr, io_ptw_resp_bits_hw, io_ptw_resp_bits_hx, io_ptw_resp_bits_hr, newEntry_pw, newEntry_px, newEntry_pr, newEntry_ppp, newEntry_pal, newEntry_paa, newEntry_eff, newEntry_c, 1'h0};	// @[PTW.scala:149:35, :151:40, :153:35, TLB.scala:207:24, :330:30, :415:19, :421:66, :422:70, :426:65, :442:18, :445:25]
    end
    superpage_entries_3_valid_0 <= ~(_T_987 | io_sfence_valid & ~superpage_entries_3_tag_v) & (_GEN_27 ? ~invalidate_refill : superpage_entries_3_valid_0);	// @[TLB.scala:206:16, :210:46, :213:{19,32,36}, :330:30, :399:88, :438:20, :465:70, :471:34, :707:19, :712:42, :717:46, :721:{24,41}]
    if (_GEN_23) begin	// @[TLB.scala:201:18, :335:56, :438:20, :465:70]
      special_entry_level <= io_ptw_resp_bits_level;	// @[TLB.scala:335:56]
      special_entry_tag_vpn <= r_refill_tag;	// @[TLB.scala:335:56, :343:25]
      special_entry_tag_v <= refill_v;	// @[TLB.scala:335:56, :440:33]
      special_entry_data_0 <= {io_ptw_resp_bits_pte_ppn[19:0], io_ptw_resp_bits_pte_u, newEntry_g, io_ptw_resp_bits_ae_ptw, io_ptw_resp_bits_ae_final, io_ptw_resp_bits_pf, io_ptw_resp_bits_gf, newEntry_sw, newEntry_sx, newEntry_sr, io_ptw_resp_bits_hw, io_ptw_resp_bits_hx, io_ptw_resp_bits_hr, newEntry_pw, newEntry_px, newEntry_pr, newEntry_ppp, newEntry_pal, newEntry_paa, newEntry_eff, newEntry_c, 1'h0};	// @[PTW.scala:149:35, :151:40, :153:35, TLB.scala:207:24, :335:56, :415:19, :421:66, :422:70, :426:65, :442:18, :445:25]
    end
    special_entry_valid_0 <= ~(_T_987 | io_sfence_valid & ~special_entry_tag_v) & (_GEN_23 | special_entry_valid_0);	// @[TLB.scala:201:18, :206:16, :210:46, :213:{19,32,36}, :335:56, :438:20, :465:70, :707:19, :712:42, :717:46, :721:{24,41}]
    if (_T_21) begin	// @[TLB.scala:668:23]
      r_refill_tag <= io_req_bits_vaddr[38:12];	// @[TLB.scala:324:30, :343:25]
      if (&{superpage_entries_3_valid_0, superpage_entries_2_valid_0, superpage_entries_1_valid_0, superpage_entries_0_valid_0})	// @[Cat.scala:33:92, TLB.scala:330:30, :746:16]
        r_superpage_repl_addr <= {state_reg_1[2], state_reg_1[2] ? state_reg_1[1] : state_reg_1[0]};	// @[Cat.scala:33:92, Replacement.scala:168:70, :243:38, :245:38, :250:16, TLB.scala:344:34, package.scala:155:13]
      else if (_GEN_22[0])	// @[OneHot.scala:47:45, TLB.scala:746:43]
        r_superpage_repl_addr <= 2'h0;	// @[TLB.scala:344:34]
      else if (_GEN_22[1])	// @[OneHot.scala:47:45, TLB.scala:746:43]
        r_superpage_repl_addr <= 2'h1;	// @[TLB.scala:344:34, package.scala:16:47]
      else	// @[OneHot.scala:47:45]
        r_superpage_repl_addr <= {1'h1, ~(_GEN_22[2])};	// @[Mux.scala:47:70, OneHot.scala:47:45, TLB.scala:344:34, :746:43]
      r_sectored_hit_valid <= (sectored_entries_0_0_valid_0 | sectored_entries_0_0_valid_1 | sectored_entries_0_0_valid_2 | sectored_entries_0_0_valid_3) & _sector_hits_T_4 == 25'h0 & ~sectored_entries_0_0_tag_v;	// @[TLB.scala:162:55, :164:{61,86,105}, :328:29, :346:27, package.scala:73:59]
      r_need_gpa <= |real_hits;	// @[Cat.scala:33:92, TLB.scala:350:23, :601:43]
    end
    r_vstage1_en <= ~_T_21 & r_vstage1_en;	// @[TLB.scala:348:25, :668:{23,36}, :672:20]
    r_stage2_en <= ~_T_21 & r_stage2_en;	// @[TLB.scala:348:25, :349:24, :668:{23,36}, :672:20, :673:19]
    if (reset) begin
      state <= 2'h0;	// @[TLB.scala:341:22]
      state_reg_1 <= 3'h0;	// @[Replacement.scala:168:70]
    end
    else begin
      if (io_ptw_resp_valid)
        state <= 2'h0;	// @[TLB.scala:341:22]
      else if (state == 2'h2 & io_sfence_valid)	// @[TLB.scala:187:28, :341:22, :698:{17,28}]
        state <= 2'h3;	// @[TLB.scala:341:22, package.scala:16:47]
      else if (_T_22) begin	// @[package.scala:16:47]
        if (io_ptw_req_ready)
          state <= {1'h1, io_sfence_valid};	// @[TLB.scala:341:22, :693:45]
        else if (io_sfence_valid)
          state <= 2'h0;	// @[TLB.scala:341:22]
        else if (_T_21)	// @[TLB.scala:668:23]
          state <= 2'h1;	// @[TLB.scala:341:22, package.scala:16:47]
      end
      else if (_T_21)	// @[TLB.scala:668:23]
        state <= 2'h1;	// @[TLB.scala:341:22, package.scala:16:47]
      if (io_req_valid & vm_enabled & (superpage_entries_0_valid_0 & ~superpage_entries_0_tag_v & _GEN_10[17:9] == 9'h0 & (superpage_hits_ignore_1 | _GEN_10[8:0] == 9'h0) | superpage_hits_1 | superpage_hits_2 | superpage_hits_3))	// @[Replacement.scala:168:70, :172:15, TLB.scala:168:43, :172:28, :173:{29,40,52,58,79}, :330:30, :388:61, :608:37, :611:31, package.scala:73:59]
        state_reg_1 <= {~(|hi_1), (|hi_1) ? ~_T_16 : state_reg_1[1], (|hi_1) ? state_reg_1[0] : ~_T_16};	// @[Cat.scala:33:92, OneHot.scala:30:18, :32:{14,28}, Replacement.scala:168:70, :196:33, :198:38, :203:16, :206:16, :218:7, package.scala:155:13]
    end
  end // always @(posedge)
  `ifndef SYNTHESIS
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM_0;
    logic [31:0] _RANDOM_1;
    logic [31:0] _RANDOM_2;
    logic [31:0] _RANDOM_3;
    logic [31:0] _RANDOM_4;
    logic [31:0] _RANDOM_5;
    logic [31:0] _RANDOM_6;
    logic [31:0] _RANDOM_7;
    logic [31:0] _RANDOM_8;
    logic [31:0] _RANDOM_9;
    logic [31:0] _RANDOM_10;
    logic [31:0] _RANDOM_11;
    logic [31:0] _RANDOM_12;
    logic [31:0] _RANDOM_13;
    logic [31:0] _RANDOM_14;
    logic [31:0] _RANDOM_15;
    logic [31:0] _RANDOM_16;
    logic [31:0] _RANDOM_17;
    logic [31:0] _RANDOM_18;
    logic [31:0] _RANDOM_19;
    logic [31:0] _RANDOM_20;
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        _RANDOM_0 = `RANDOM;
        _RANDOM_1 = `RANDOM;
        _RANDOM_2 = `RANDOM;
        _RANDOM_3 = `RANDOM;
        _RANDOM_4 = `RANDOM;
        _RANDOM_5 = `RANDOM;
        _RANDOM_6 = `RANDOM;
        _RANDOM_7 = `RANDOM;
        _RANDOM_8 = `RANDOM;
        _RANDOM_9 = `RANDOM;
        _RANDOM_10 = `RANDOM;
        _RANDOM_11 = `RANDOM;
        _RANDOM_12 = `RANDOM;
        _RANDOM_13 = `RANDOM;
        _RANDOM_14 = `RANDOM;
        _RANDOM_15 = `RANDOM;
        _RANDOM_16 = `RANDOM;
        _RANDOM_17 = `RANDOM;
        _RANDOM_18 = `RANDOM;
        _RANDOM_19 = `RANDOM;
        _RANDOM_20 = `RANDOM;
        sectored_entries_0_0_tag_vpn = _RANDOM_0[28:2];	// @[TLB.scala:328:29]
        sectored_entries_0_0_tag_v = _RANDOM_0[29];	// @[TLB.scala:328:29]
        sectored_entries_0_0_data_0 = {_RANDOM_0[31:30], _RANDOM_1, _RANDOM_2[6:0]};	// @[TLB.scala:328:29]
        sectored_entries_0_0_data_1 = {_RANDOM_2[31:7], _RANDOM_3[15:0]};	// @[TLB.scala:328:29]
        sectored_entries_0_0_data_2 = {_RANDOM_3[31:16], _RANDOM_4[24:0]};	// @[TLB.scala:328:29]
        sectored_entries_0_0_data_3 = {_RANDOM_4[31:25], _RANDOM_5, _RANDOM_6[1:0]};	// @[TLB.scala:328:29]
        sectored_entries_0_0_valid_0 = _RANDOM_6[2];	// @[TLB.scala:328:29]
        sectored_entries_0_0_valid_1 = _RANDOM_6[3];	// @[TLB.scala:328:29]
        sectored_entries_0_0_valid_2 = _RANDOM_6[4];	// @[TLB.scala:328:29]
        sectored_entries_0_0_valid_3 = _RANDOM_6[5];	// @[TLB.scala:328:29]
        superpage_entries_0_level = _RANDOM_6[7:6];	// @[TLB.scala:328:29, :330:30]
        superpage_entries_0_tag_vpn = {_RANDOM_6[31:8], _RANDOM_7[2:0]};	// @[TLB.scala:328:29, :330:30]
        superpage_entries_0_tag_v = _RANDOM_7[3];	// @[TLB.scala:330:30]
        superpage_entries_0_data_0 = {_RANDOM_7[31:4], _RANDOM_8[12:0]};	// @[TLB.scala:330:30]
        superpage_entries_0_valid_0 = _RANDOM_8[13];	// @[TLB.scala:330:30]
        superpage_entries_1_level = _RANDOM_8[15:14];	// @[TLB.scala:330:30]
        superpage_entries_1_tag_vpn = {_RANDOM_8[31:16], _RANDOM_9[10:0]};	// @[TLB.scala:330:30]
        superpage_entries_1_tag_v = _RANDOM_9[11];	// @[TLB.scala:330:30]
        superpage_entries_1_data_0 = {_RANDOM_9[31:12], _RANDOM_10[20:0]};	// @[TLB.scala:330:30]
        superpage_entries_1_valid_0 = _RANDOM_10[21];	// @[TLB.scala:330:30]
        superpage_entries_2_level = _RANDOM_10[23:22];	// @[TLB.scala:330:30]
        superpage_entries_2_tag_vpn = {_RANDOM_10[31:24], _RANDOM_11[18:0]};	// @[TLB.scala:330:30]
        superpage_entries_2_tag_v = _RANDOM_11[19];	// @[TLB.scala:330:30]
        superpage_entries_2_data_0 = {_RANDOM_11[31:20], _RANDOM_12[28:0]};	// @[TLB.scala:330:30]
        superpage_entries_2_valid_0 = _RANDOM_12[29];	// @[TLB.scala:330:30]
        superpage_entries_3_level = _RANDOM_12[31:30];	// @[TLB.scala:330:30]
        superpage_entries_3_tag_vpn = _RANDOM_13[26:0];	// @[TLB.scala:330:30]
        superpage_entries_3_tag_v = _RANDOM_13[27];	// @[TLB.scala:330:30]
        superpage_entries_3_data_0 = {_RANDOM_13[31:28], _RANDOM_14, _RANDOM_15[4:0]};	// @[TLB.scala:330:30]
        superpage_entries_3_valid_0 = _RANDOM_15[5];	// @[TLB.scala:330:30]
        special_entry_level = _RANDOM_15[7:6];	// @[TLB.scala:330:30, :335:56]
        special_entry_tag_vpn = {_RANDOM_15[31:8], _RANDOM_16[2:0]};	// @[TLB.scala:330:30, :335:56]
        special_entry_tag_v = _RANDOM_16[3];	// @[TLB.scala:335:56]
        special_entry_data_0 = {_RANDOM_16[31:4], _RANDOM_17[12:0]};	// @[TLB.scala:335:56]
        special_entry_valid_0 = _RANDOM_17[13];	// @[TLB.scala:335:56]
        state = _RANDOM_17[15:14];	// @[TLB.scala:335:56, :341:22]
        r_refill_tag = {_RANDOM_17[31:16], _RANDOM_18[10:0]};	// @[TLB.scala:335:56, :343:25]
        r_superpage_repl_addr = _RANDOM_18[12:11];	// @[TLB.scala:343:25, :344:34]
        r_sectored_hit_valid = _RANDOM_18[13];	// @[TLB.scala:343:25, :346:27]
        r_vstage1_en = _RANDOM_18[17];	// @[TLB.scala:343:25, :348:25]
        r_stage2_en = _RANDOM_18[18];	// @[TLB.scala:343:25, :349:24]
        r_need_gpa = _RANDOM_18[19];	// @[TLB.scala:343:25, :350:23]
        state_reg_1 = _RANDOM_20[27:25];	// @[Replacement.scala:168:70]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // not def SYNTHESIS
  OptimizationBarrier mpu_ppn_barrier (	// @[package.scala:259:25]
    .io_x_ppn      (special_entry_data_0[40:21]),	// @[TLB.scala:160:77, :335:56]
    .io_x_u        (special_entry_data_0[20]),	// @[TLB.scala:160:77, :335:56]
    .io_x_ae_ptw   (special_entry_data_0[18]),	// @[TLB.scala:160:77, :335:56]
    .io_x_ae_final (special_entry_data_0[17]),	// @[TLB.scala:160:77, :335:56]
    .io_x_pf       (special_entry_data_0[16]),	// @[TLB.scala:160:77, :335:56]
    .io_x_gf       (special_entry_data_0[15]),	// @[TLB.scala:160:77, :335:56]
    .io_x_sw       (special_entry_data_0[14]),	// @[TLB.scala:160:77, :335:56]
    .io_x_sx       (special_entry_data_0[13]),	// @[TLB.scala:160:77, :335:56]
    .io_x_sr       (special_entry_data_0[12]),	// @[TLB.scala:160:77, :335:56]
    .io_x_pw       (special_entry_data_0[8]),	// @[TLB.scala:160:77, :335:56]
    .io_x_px       (special_entry_data_0[7]),	// @[TLB.scala:160:77, :335:56]
    .io_x_pr       (special_entry_data_0[6]),	// @[TLB.scala:160:77, :335:56]
    .io_x_ppp      (special_entry_data_0[5]),	// @[TLB.scala:160:77, :335:56]
    .io_x_pal      (special_entry_data_0[4]),	// @[TLB.scala:160:77, :335:56]
    .io_x_paa      (special_entry_data_0[3]),	// @[TLB.scala:160:77, :335:56]
    .io_x_eff      (special_entry_data_0[2]),	// @[TLB.scala:160:77, :335:56]
    .io_x_c        (special_entry_data_0[1]),	// @[TLB.scala:160:77, :335:56]
    .io_y_ppn      (_mpu_ppn_barrier_io_y_ppn),
    .io_y_u        (_mpu_ppn_barrier_io_y_u),
    .io_y_ae_ptw   (_mpu_ppn_barrier_io_y_ae_ptw),
    .io_y_ae_final (_mpu_ppn_barrier_io_y_ae_final),
    .io_y_pf       (_mpu_ppn_barrier_io_y_pf),
    .io_y_gf       (_mpu_ppn_barrier_io_y_gf),
    .io_y_sw       (_mpu_ppn_barrier_io_y_sw),
    .io_y_sx       (_mpu_ppn_barrier_io_y_sx),
    .io_y_sr       (_mpu_ppn_barrier_io_y_sr),
    .io_y_pw       (_mpu_ppn_barrier_io_y_pw),
    .io_y_px       (_mpu_ppn_barrier_io_y_px),
    .io_y_pr       (_mpu_ppn_barrier_io_y_pr),
    .io_y_ppp      (_mpu_ppn_barrier_io_y_ppp),
    .io_y_pal      (_mpu_ppn_barrier_io_y_pal),
    .io_y_paa      (_mpu_ppn_barrier_io_y_paa),
    .io_y_eff      (_mpu_ppn_barrier_io_y_eff),
    .io_y_c        (_mpu_ppn_barrier_io_y_c)
  );
  PMPChecker_2 pmp (	// @[TLB.scala:405:19]
    .io_prv         (mpu_priv[1:0]),	// @[TLB.scala:404:27, :409:14]
    .io_pmp_0_cfg_l (io_ptw_pmp_0_cfg_l),
    .io_pmp_0_cfg_a (io_ptw_pmp_0_cfg_a),
    .io_pmp_0_cfg_x (io_ptw_pmp_0_cfg_x),
    .io_pmp_0_cfg_w (io_ptw_pmp_0_cfg_w),
    .io_pmp_0_cfg_r (io_ptw_pmp_0_cfg_r),
    .io_pmp_0_addr  (io_ptw_pmp_0_addr),
    .io_pmp_0_mask  (io_ptw_pmp_0_mask),
    .io_pmp_1_cfg_l (io_ptw_pmp_1_cfg_l),
    .io_pmp_1_cfg_a (io_ptw_pmp_1_cfg_a),
    .io_pmp_1_cfg_x (io_ptw_pmp_1_cfg_x),
    .io_pmp_1_cfg_w (io_ptw_pmp_1_cfg_w),
    .io_pmp_1_cfg_r (io_ptw_pmp_1_cfg_r),
    .io_pmp_1_addr  (io_ptw_pmp_1_addr),
    .io_pmp_1_mask  (io_ptw_pmp_1_mask),
    .io_pmp_2_cfg_l (io_ptw_pmp_2_cfg_l),
    .io_pmp_2_cfg_a (io_ptw_pmp_2_cfg_a),
    .io_pmp_2_cfg_x (io_ptw_pmp_2_cfg_x),
    .io_pmp_2_cfg_w (io_ptw_pmp_2_cfg_w),
    .io_pmp_2_cfg_r (io_ptw_pmp_2_cfg_r),
    .io_pmp_2_addr  (io_ptw_pmp_2_addr),
    .io_pmp_2_mask  (io_ptw_pmp_2_mask),
    .io_pmp_3_cfg_l (io_ptw_pmp_3_cfg_l),
    .io_pmp_3_cfg_a (io_ptw_pmp_3_cfg_a),
    .io_pmp_3_cfg_x (io_ptw_pmp_3_cfg_x),
    .io_pmp_3_cfg_w (io_ptw_pmp_3_cfg_w),
    .io_pmp_3_cfg_r (io_ptw_pmp_3_cfg_r),
    .io_pmp_3_addr  (io_ptw_pmp_3_addr),
    .io_pmp_3_mask  (io_ptw_pmp_3_mask),
    .io_pmp_4_cfg_l (io_ptw_pmp_4_cfg_l),
    .io_pmp_4_cfg_a (io_ptw_pmp_4_cfg_a),
    .io_pmp_4_cfg_x (io_ptw_pmp_4_cfg_x),
    .io_pmp_4_cfg_w (io_ptw_pmp_4_cfg_w),
    .io_pmp_4_cfg_r (io_ptw_pmp_4_cfg_r),
    .io_pmp_4_addr  (io_ptw_pmp_4_addr),
    .io_pmp_4_mask  (io_ptw_pmp_4_mask),
    .io_pmp_5_cfg_l (io_ptw_pmp_5_cfg_l),
    .io_pmp_5_cfg_a (io_ptw_pmp_5_cfg_a),
    .io_pmp_5_cfg_x (io_ptw_pmp_5_cfg_x),
    .io_pmp_5_cfg_w (io_ptw_pmp_5_cfg_w),
    .io_pmp_5_cfg_r (io_ptw_pmp_5_cfg_r),
    .io_pmp_5_addr  (io_ptw_pmp_5_addr),
    .io_pmp_5_mask  (io_ptw_pmp_5_mask),
    .io_pmp_6_cfg_l (io_ptw_pmp_6_cfg_l),
    .io_pmp_6_cfg_a (io_ptw_pmp_6_cfg_a),
    .io_pmp_6_cfg_x (io_ptw_pmp_6_cfg_x),
    .io_pmp_6_cfg_w (io_ptw_pmp_6_cfg_w),
    .io_pmp_6_cfg_r (io_ptw_pmp_6_cfg_r),
    .io_pmp_6_addr  (io_ptw_pmp_6_addr),
    .io_pmp_6_mask  (io_ptw_pmp_6_mask),
    .io_pmp_7_cfg_l (io_ptw_pmp_7_cfg_l),
    .io_pmp_7_cfg_a (io_ptw_pmp_7_cfg_a),
    .io_pmp_7_cfg_x (io_ptw_pmp_7_cfg_x),
    .io_pmp_7_cfg_w (io_ptw_pmp_7_cfg_w),
    .io_pmp_7_cfg_r (io_ptw_pmp_7_cfg_r),
    .io_pmp_7_addr  (io_ptw_pmp_7_addr),
    .io_pmp_7_mask  (io_ptw_pmp_7_mask),
    .io_addr        ({mpu_ppn[19:0], io_req_bits_vaddr[11:0]}),	// @[TLB.scala:401:20, :403:52, :406:15]
    .io_size        (io_req_bits_size),
    .io_r           (_pmp_io_r),
    .io_w           (_pmp_io_w),
    .io_x           (_pmp_io_x)
  );
  OptimizationBarrier entries_barrier (	// @[package.scala:259:25]
    .io_x_ppn      (_entries_WIRE_1[40:21]),	// @[TLB.scala:160:77]
    .io_x_u        (_entries_WIRE_1[20]),	// @[TLB.scala:160:77]
    .io_x_ae_ptw   (_entries_WIRE_1[18]),	// @[TLB.scala:160:77]
    .io_x_ae_final (_entries_WIRE_1[17]),	// @[TLB.scala:160:77]
    .io_x_pf       (_entries_WIRE_1[16]),	// @[TLB.scala:160:77]
    .io_x_gf       (_entries_WIRE_1[15]),	// @[TLB.scala:160:77]
    .io_x_sw       (_entries_WIRE_1[14]),	// @[TLB.scala:160:77]
    .io_x_sx       (_entries_WIRE_1[13]),	// @[TLB.scala:160:77]
    .io_x_sr       (_entries_WIRE_1[12]),	// @[TLB.scala:160:77]
    .io_x_pw       (_entries_WIRE_1[8]),	// @[TLB.scala:160:77]
    .io_x_px       (_entries_WIRE_1[7]),	// @[TLB.scala:160:77]
    .io_x_pr       (_entries_WIRE_1[6]),	// @[TLB.scala:160:77]
    .io_x_ppp      (_entries_WIRE_1[5]),	// @[TLB.scala:160:77]
    .io_x_pal      (_entries_WIRE_1[4]),	// @[TLB.scala:160:77]
    .io_x_paa      (_entries_WIRE_1[3]),	// @[TLB.scala:160:77]
    .io_x_eff      (_entries_WIRE_1[2]),	// @[TLB.scala:160:77]
    .io_x_c        (_entries_WIRE_1[1]),	// @[TLB.scala:160:77]
    .io_y_ppn      (_entries_barrier_io_y_ppn),
    .io_y_u        (_entries_barrier_io_y_u),
    .io_y_ae_ptw   (_entries_barrier_io_y_ae_ptw),
    .io_y_ae_final (_entries_barrier_io_y_ae_final),
    .io_y_pf       (_entries_barrier_io_y_pf),
    .io_y_gf       (_entries_barrier_io_y_gf),
    .io_y_sw       (_entries_barrier_io_y_sw),
    .io_y_sx       (_entries_barrier_io_y_sx),
    .io_y_sr       (_entries_barrier_io_y_sr),
    .io_y_pw       (_entries_barrier_io_y_pw),
    .io_y_px       (_entries_barrier_io_y_px),
    .io_y_pr       (_entries_barrier_io_y_pr),
    .io_y_ppp      (_entries_barrier_io_y_ppp),
    .io_y_pal      (_entries_barrier_io_y_pal),
    .io_y_paa      (_entries_barrier_io_y_paa),
    .io_y_eff      (_entries_barrier_io_y_eff),
    .io_y_c        (_entries_barrier_io_y_c)
  );
  OptimizationBarrier entries_barrier_1 (	// @[package.scala:259:25]
    .io_x_ppn      (superpage_entries_0_data_0[40:21]),	// @[TLB.scala:160:77, :330:30]
    .io_x_u        (superpage_entries_0_data_0[20]),	// @[TLB.scala:160:77, :330:30]
    .io_x_ae_ptw   (superpage_entries_0_data_0[18]),	// @[TLB.scala:160:77, :330:30]
    .io_x_ae_final (superpage_entries_0_data_0[17]),	// @[TLB.scala:160:77, :330:30]
    .io_x_pf       (superpage_entries_0_data_0[16]),	// @[TLB.scala:160:77, :330:30]
    .io_x_gf       (superpage_entries_0_data_0[15]),	// @[TLB.scala:160:77, :330:30]
    .io_x_sw       (superpage_entries_0_data_0[14]),	// @[TLB.scala:160:77, :330:30]
    .io_x_sx       (superpage_entries_0_data_0[13]),	// @[TLB.scala:160:77, :330:30]
    .io_x_sr       (superpage_entries_0_data_0[12]),	// @[TLB.scala:160:77, :330:30]
    .io_x_pw       (superpage_entries_0_data_0[8]),	// @[TLB.scala:160:77, :330:30]
    .io_x_px       (superpage_entries_0_data_0[7]),	// @[TLB.scala:160:77, :330:30]
    .io_x_pr       (superpage_entries_0_data_0[6]),	// @[TLB.scala:160:77, :330:30]
    .io_x_ppp      (superpage_entries_0_data_0[5]),	// @[TLB.scala:160:77, :330:30]
    .io_x_pal      (superpage_entries_0_data_0[4]),	// @[TLB.scala:160:77, :330:30]
    .io_x_paa      (superpage_entries_0_data_0[3]),	// @[TLB.scala:160:77, :330:30]
    .io_x_eff      (superpage_entries_0_data_0[2]),	// @[TLB.scala:160:77, :330:30]
    .io_x_c        (superpage_entries_0_data_0[1]),	// @[TLB.scala:160:77, :330:30]
    .io_y_ppn      (_entries_barrier_1_io_y_ppn),
    .io_y_u        (_entries_barrier_1_io_y_u),
    .io_y_ae_ptw   (_entries_barrier_1_io_y_ae_ptw),
    .io_y_ae_final (_entries_barrier_1_io_y_ae_final),
    .io_y_pf       (_entries_barrier_1_io_y_pf),
    .io_y_gf       (_entries_barrier_1_io_y_gf),
    .io_y_sw       (_entries_barrier_1_io_y_sw),
    .io_y_sx       (_entries_barrier_1_io_y_sx),
    .io_y_sr       (_entries_barrier_1_io_y_sr),
    .io_y_pw       (_entries_barrier_1_io_y_pw),
    .io_y_px       (_entries_barrier_1_io_y_px),
    .io_y_pr       (_entries_barrier_1_io_y_pr),
    .io_y_ppp      (_entries_barrier_1_io_y_ppp),
    .io_y_pal      (_entries_barrier_1_io_y_pal),
    .io_y_paa      (_entries_barrier_1_io_y_paa),
    .io_y_eff      (_entries_barrier_1_io_y_eff),
    .io_y_c        (_entries_barrier_1_io_y_c)
  );
  OptimizationBarrier entries_barrier_2 (	// @[package.scala:259:25]
    .io_x_ppn      (superpage_entries_1_data_0[40:21]),	// @[TLB.scala:160:77, :330:30]
    .io_x_u        (superpage_entries_1_data_0[20]),	// @[TLB.scala:160:77, :330:30]
    .io_x_ae_ptw   (superpage_entries_1_data_0[18]),	// @[TLB.scala:160:77, :330:30]
    .io_x_ae_final (superpage_entries_1_data_0[17]),	// @[TLB.scala:160:77, :330:30]
    .io_x_pf       (superpage_entries_1_data_0[16]),	// @[TLB.scala:160:77, :330:30]
    .io_x_gf       (superpage_entries_1_data_0[15]),	// @[TLB.scala:160:77, :330:30]
    .io_x_sw       (superpage_entries_1_data_0[14]),	// @[TLB.scala:160:77, :330:30]
    .io_x_sx       (superpage_entries_1_data_0[13]),	// @[TLB.scala:160:77, :330:30]
    .io_x_sr       (superpage_entries_1_data_0[12]),	// @[TLB.scala:160:77, :330:30]
    .io_x_pw       (superpage_entries_1_data_0[8]),	// @[TLB.scala:160:77, :330:30]
    .io_x_px       (superpage_entries_1_data_0[7]),	// @[TLB.scala:160:77, :330:30]
    .io_x_pr       (superpage_entries_1_data_0[6]),	// @[TLB.scala:160:77, :330:30]
    .io_x_ppp      (superpage_entries_1_data_0[5]),	// @[TLB.scala:160:77, :330:30]
    .io_x_pal      (superpage_entries_1_data_0[4]),	// @[TLB.scala:160:77, :330:30]
    .io_x_paa      (superpage_entries_1_data_0[3]),	// @[TLB.scala:160:77, :330:30]
    .io_x_eff      (superpage_entries_1_data_0[2]),	// @[TLB.scala:160:77, :330:30]
    .io_x_c        (superpage_entries_1_data_0[1]),	// @[TLB.scala:160:77, :330:30]
    .io_y_ppn      (_entries_barrier_2_io_y_ppn),
    .io_y_u        (_entries_barrier_2_io_y_u),
    .io_y_ae_ptw   (_entries_barrier_2_io_y_ae_ptw),
    .io_y_ae_final (_entries_barrier_2_io_y_ae_final),
    .io_y_pf       (_entries_barrier_2_io_y_pf),
    .io_y_gf       (_entries_barrier_2_io_y_gf),
    .io_y_sw       (_entries_barrier_2_io_y_sw),
    .io_y_sx       (_entries_barrier_2_io_y_sx),
    .io_y_sr       (_entries_barrier_2_io_y_sr),
    .io_y_pw       (_entries_barrier_2_io_y_pw),
    .io_y_px       (_entries_barrier_2_io_y_px),
    .io_y_pr       (_entries_barrier_2_io_y_pr),
    .io_y_ppp      (_entries_barrier_2_io_y_ppp),
    .io_y_pal      (_entries_barrier_2_io_y_pal),
    .io_y_paa      (_entries_barrier_2_io_y_paa),
    .io_y_eff      (_entries_barrier_2_io_y_eff),
    .io_y_c        (_entries_barrier_2_io_y_c)
  );
  OptimizationBarrier entries_barrier_3 (	// @[package.scala:259:25]
    .io_x_ppn      (superpage_entries_2_data_0[40:21]),	// @[TLB.scala:160:77, :330:30]
    .io_x_u        (superpage_entries_2_data_0[20]),	// @[TLB.scala:160:77, :330:30]
    .io_x_ae_ptw   (superpage_entries_2_data_0[18]),	// @[TLB.scala:160:77, :330:30]
    .io_x_ae_final (superpage_entries_2_data_0[17]),	// @[TLB.scala:160:77, :330:30]
    .io_x_pf       (superpage_entries_2_data_0[16]),	// @[TLB.scala:160:77, :330:30]
    .io_x_gf       (superpage_entries_2_data_0[15]),	// @[TLB.scala:160:77, :330:30]
    .io_x_sw       (superpage_entries_2_data_0[14]),	// @[TLB.scala:160:77, :330:30]
    .io_x_sx       (superpage_entries_2_data_0[13]),	// @[TLB.scala:160:77, :330:30]
    .io_x_sr       (superpage_entries_2_data_0[12]),	// @[TLB.scala:160:77, :330:30]
    .io_x_pw       (superpage_entries_2_data_0[8]),	// @[TLB.scala:160:77, :330:30]
    .io_x_px       (superpage_entries_2_data_0[7]),	// @[TLB.scala:160:77, :330:30]
    .io_x_pr       (superpage_entries_2_data_0[6]),	// @[TLB.scala:160:77, :330:30]
    .io_x_ppp      (superpage_entries_2_data_0[5]),	// @[TLB.scala:160:77, :330:30]
    .io_x_pal      (superpage_entries_2_data_0[4]),	// @[TLB.scala:160:77, :330:30]
    .io_x_paa      (superpage_entries_2_data_0[3]),	// @[TLB.scala:160:77, :330:30]
    .io_x_eff      (superpage_entries_2_data_0[2]),	// @[TLB.scala:160:77, :330:30]
    .io_x_c        (superpage_entries_2_data_0[1]),	// @[TLB.scala:160:77, :330:30]
    .io_y_ppn      (_entries_barrier_3_io_y_ppn),
    .io_y_u        (_entries_barrier_3_io_y_u),
    .io_y_ae_ptw   (_entries_barrier_3_io_y_ae_ptw),
    .io_y_ae_final (_entries_barrier_3_io_y_ae_final),
    .io_y_pf       (_entries_barrier_3_io_y_pf),
    .io_y_gf       (_entries_barrier_3_io_y_gf),
    .io_y_sw       (_entries_barrier_3_io_y_sw),
    .io_y_sx       (_entries_barrier_3_io_y_sx),
    .io_y_sr       (_entries_barrier_3_io_y_sr),
    .io_y_pw       (_entries_barrier_3_io_y_pw),
    .io_y_px       (_entries_barrier_3_io_y_px),
    .io_y_pr       (_entries_barrier_3_io_y_pr),
    .io_y_ppp      (_entries_barrier_3_io_y_ppp),
    .io_y_pal      (_entries_barrier_3_io_y_pal),
    .io_y_paa      (_entries_barrier_3_io_y_paa),
    .io_y_eff      (_entries_barrier_3_io_y_eff),
    .io_y_c        (_entries_barrier_3_io_y_c)
  );
  OptimizationBarrier entries_barrier_4 (	// @[package.scala:259:25]
    .io_x_ppn      (superpage_entries_3_data_0[40:21]),	// @[TLB.scala:160:77, :330:30]
    .io_x_u        (superpage_entries_3_data_0[20]),	// @[TLB.scala:160:77, :330:30]
    .io_x_ae_ptw   (superpage_entries_3_data_0[18]),	// @[TLB.scala:160:77, :330:30]
    .io_x_ae_final (superpage_entries_3_data_0[17]),	// @[TLB.scala:160:77, :330:30]
    .io_x_pf       (superpage_entries_3_data_0[16]),	// @[TLB.scala:160:77, :330:30]
    .io_x_gf       (superpage_entries_3_data_0[15]),	// @[TLB.scala:160:77, :330:30]
    .io_x_sw       (superpage_entries_3_data_0[14]),	// @[TLB.scala:160:77, :330:30]
    .io_x_sx       (superpage_entries_3_data_0[13]),	// @[TLB.scala:160:77, :330:30]
    .io_x_sr       (superpage_entries_3_data_0[12]),	// @[TLB.scala:160:77, :330:30]
    .io_x_pw       (superpage_entries_3_data_0[8]),	// @[TLB.scala:160:77, :330:30]
    .io_x_px       (superpage_entries_3_data_0[7]),	// @[TLB.scala:160:77, :330:30]
    .io_x_pr       (superpage_entries_3_data_0[6]),	// @[TLB.scala:160:77, :330:30]
    .io_x_ppp      (superpage_entries_3_data_0[5]),	// @[TLB.scala:160:77, :330:30]
    .io_x_pal      (superpage_entries_3_data_0[4]),	// @[TLB.scala:160:77, :330:30]
    .io_x_paa      (superpage_entries_3_data_0[3]),	// @[TLB.scala:160:77, :330:30]
    .io_x_eff      (superpage_entries_3_data_0[2]),	// @[TLB.scala:160:77, :330:30]
    .io_x_c        (superpage_entries_3_data_0[1]),	// @[TLB.scala:160:77, :330:30]
    .io_y_ppn      (_entries_barrier_4_io_y_ppn),
    .io_y_u        (_entries_barrier_4_io_y_u),
    .io_y_ae_ptw   (_entries_barrier_4_io_y_ae_ptw),
    .io_y_ae_final (_entries_barrier_4_io_y_ae_final),
    .io_y_pf       (_entries_barrier_4_io_y_pf),
    .io_y_gf       (_entries_barrier_4_io_y_gf),
    .io_y_sw       (_entries_barrier_4_io_y_sw),
    .io_y_sx       (_entries_barrier_4_io_y_sx),
    .io_y_sr       (_entries_barrier_4_io_y_sr),
    .io_y_pw       (_entries_barrier_4_io_y_pw),
    .io_y_px       (_entries_barrier_4_io_y_px),
    .io_y_pr       (_entries_barrier_4_io_y_pr),
    .io_y_ppp      (_entries_barrier_4_io_y_ppp),
    .io_y_pal      (_entries_barrier_4_io_y_pal),
    .io_y_paa      (_entries_barrier_4_io_y_paa),
    .io_y_eff      (_entries_barrier_4_io_y_eff),
    .io_y_c        (_entries_barrier_4_io_y_c)
  );
  OptimizationBarrier entries_barrier_5 (	// @[package.scala:259:25]
    .io_x_ppn      (special_entry_data_0[40:21]),	// @[TLB.scala:160:77, :335:56]
    .io_x_u        (special_entry_data_0[20]),	// @[TLB.scala:160:77, :335:56]
    .io_x_ae_ptw   (special_entry_data_0[18]),	// @[TLB.scala:160:77, :335:56]
    .io_x_ae_final (special_entry_data_0[17]),	// @[TLB.scala:160:77, :335:56]
    .io_x_pf       (special_entry_data_0[16]),	// @[TLB.scala:160:77, :335:56]
    .io_x_gf       (special_entry_data_0[15]),	// @[TLB.scala:160:77, :335:56]
    .io_x_sw       (special_entry_data_0[14]),	// @[TLB.scala:160:77, :335:56]
    .io_x_sx       (special_entry_data_0[13]),	// @[TLB.scala:160:77, :335:56]
    .io_x_sr       (special_entry_data_0[12]),	// @[TLB.scala:160:77, :335:56]
    .io_x_pw       (special_entry_data_0[8]),	// @[TLB.scala:160:77, :335:56]
    .io_x_px       (special_entry_data_0[7]),	// @[TLB.scala:160:77, :335:56]
    .io_x_pr       (special_entry_data_0[6]),	// @[TLB.scala:160:77, :335:56]
    .io_x_ppp      (special_entry_data_0[5]),	// @[TLB.scala:160:77, :335:56]
    .io_x_pal      (special_entry_data_0[4]),	// @[TLB.scala:160:77, :335:56]
    .io_x_paa      (special_entry_data_0[3]),	// @[TLB.scala:160:77, :335:56]
    .io_x_eff      (special_entry_data_0[2]),	// @[TLB.scala:160:77, :335:56]
    .io_x_c        (special_entry_data_0[1]),	// @[TLB.scala:160:77, :335:56]
    .io_y_ppn      (_entries_barrier_5_io_y_ppn),
    .io_y_u        (_entries_barrier_5_io_y_u),
    .io_y_ae_ptw   (_entries_barrier_5_io_y_ae_ptw),
    .io_y_ae_final (_entries_barrier_5_io_y_ae_final),
    .io_y_pf       (_entries_barrier_5_io_y_pf),
    .io_y_gf       (_entries_barrier_5_io_y_gf),
    .io_y_sw       (_entries_barrier_5_io_y_sw),
    .io_y_sx       (_entries_barrier_5_io_y_sx),
    .io_y_sr       (_entries_barrier_5_io_y_sr),
    .io_y_pw       (_entries_barrier_5_io_y_pw),
    .io_y_px       (_entries_barrier_5_io_y_px),
    .io_y_pr       (_entries_barrier_5_io_y_pr),
    .io_y_ppp      (_entries_barrier_5_io_y_ppp),
    .io_y_pal      (_entries_barrier_5_io_y_pal),
    .io_y_paa      (_entries_barrier_5_io_y_paa),
    .io_y_eff      (_entries_barrier_5_io_y_eff),
    .io_y_c        (_entries_barrier_5_io_y_c)
  );
  assign io_resp_miss = io_ptw_resp_valid | tlb_miss | multipleHits;	// @[Misc.scala:182:49, TLB.scala:604:64, :642:64]
  assign io_resp_paddr = {(hitsVec_0 ? _entries_barrier_io_y_ppn : 20'h0) | (hitsVec_1 ? {_entries_barrier_1_io_y_ppn[19:18], (superpage_hits_ignore_1 ? io_req_bits_vaddr[29:21] : 9'h0) | _entries_barrier_1_io_y_ppn[17:9], io_req_bits_vaddr[20:12] | _entries_barrier_1_io_y_ppn[8:0]} : 20'h0) | (hitsVec_2 ? {_entries_barrier_2_io_y_ppn[19:18], (superpage_hits_ignore_4 ? io_req_bits_vaddr[29:21] : 9'h0) | _entries_barrier_2_io_y_ppn[17:9], io_req_bits_vaddr[20:12] | _entries_barrier_2_io_y_ppn[8:0]} : 20'h0) | (hitsVec_3 ? {_entries_barrier_3_io_y_ppn[19:18], (superpage_hits_ignore_7 ? io_req_bits_vaddr[29:21] : 9'h0) | _entries_barrier_3_io_y_ppn[17:9], io_req_bits_vaddr[20:12] | _entries_barrier_3_io_y_ppn[8:0]} : 20'h0) | (hitsVec_4 ? {_entries_barrier_4_io_y_ppn[19:18], (superpage_hits_ignore_10 ? io_req_bits_vaddr[29:21] : 9'h0) | _entries_barrier_4_io_y_ppn[17:9], io_req_bits_vaddr[20:12] | _entries_barrier_4_io_y_ppn[8:0]} : 20'h0) | (hitsVec_5 ? {_entries_barrier_5_io_y_ppn[19:18], _GEN | _entries_barrier_5_io_y_ppn[17:9], _GEN_0 | _entries_barrier_5_io_y_ppn[8:0]} : 20'h0) | (vm_enabled ? 20'h0 : io_req_bits_vaddr[31:12]), io_req_bits_vaddr[11:0]};	// @[Cat.scala:33:92, Mux.scala:27:73, TLB.scala:172:28, :173:79, :185:26, :188:{28,47}, :324:30, :388:61, :403:52, :432:44, :493:125, package.scala:259:25]
  assign io_resp_pf_ld = bad_va & cmd_read | (|((cmd_read ? ({1'h0, ~(priv_rw_ok & ({_entries_barrier_5_io_y_sr, _entries_barrier_4_io_y_sr, _entries_barrier_3_io_y_sr, _entries_barrier_2_io_y_sr, _entries_barrier_1_io_y_sr, _entries_barrier_io_y_sr} | (io_ptw_status_mxr ? {_entries_barrier_5_io_y_sx, _entries_barrier_4_io_y_sx, _entries_barrier_3_io_y_sx, _entries_barrier_2_io_y_sx, _entries_barrier_1_io_y_sx, _entries_barrier_io_y_sx} : 6'h0)))} & _gf_inst_array_T_1 | ptw_pf_array) & _pf_inst_array_T_4 : 7'h0) & hits));	// @[Bitwise.scala:77:12, Cat.scala:33:92, Consts.scala:85:68, TLB.scala:504:70, :511:{41,69,74}, :559:34, :587:19, :588:{24,37,71,88,104}, :624:{28,41,57,65}, package.scala:259:25]
  assign io_resp_pf_st = bad_va & cmd_write_perms | (|((cmd_write_perms ? ({1'h0, ~(priv_rw_ok & {_entries_barrier_5_io_y_sw, _entries_barrier_4_io_y_sw, _entries_barrier_3_io_y_sw, _entries_barrier_2_io_y_sw, _entries_barrier_1_io_y_sw, _entries_barrier_io_y_sw})} & _gf_inst_array_T_1 | ptw_pf_array) & _pf_inst_array_T_4 : 7'h0) & hits));	// @[Cat.scala:33:92, TLB.scala:504:70, :512:41, :559:34, :568:35, :587:19, :589:{24,44,53,70,86}, :625:{28,48,64,72}, package.scala:259:25]
  assign io_resp_ae_ld = |((cmd_read ? ae_array | ~({{2{newEntry_pr}}, _entries_barrier_4_io_y_pr, _entries_barrier_3_io_y_pr, _entries_barrier_2_io_y_pr, _entries_barrier_1_io_y_pr, _entries_barrier_io_y_pr} & {1'h1, ~_GEN_16, ~_GEN_17, ~_GEN_18, ~_GEN_19, ~_GEN_20, ~_GEN_21}) : 7'h0) & hits);	// @[Bitwise.scala:77:12, Cat.scala:33:92, Consts.scala:85:68, TLB.scala:421:66, :520:{87,89,104}, :573:37, :577:{24,44,46}, :587:19, :632:{33,41}, package.scala:259:25]
  assign io_resp_ae_st = |(((cmd_write_perms ? ae_array | ~({{2{newEntry_pw}}, _entries_barrier_4_io_y_pw, _entries_barrier_3_io_y_pw, _entries_barrier_2_io_y_pw, _entries_barrier_1_io_y_pw, _entries_barrier_io_y_pw} & {1'h1, ~_GEN_16, ~_GEN_17, ~_GEN_18, ~_GEN_19, ~_GEN_20, ~_GEN_21}) : 7'h0) | (cmd_put_partial ? ~({{2{newEntry_ppp}}, _entries_barrier_4_io_y_ppp, _entries_barrier_3_io_y_ppp, _entries_barrier_2_io_y_ppp, _entries_barrier_1_io_y_ppp, _entries_barrier_io_y_ppp} | c_array) : 7'h0) | (_cmd_write_T_5 | _cmd_write_T_6 | _cmd_write_T_7 | _cmd_write_T_8 ? ~({{2{newEntry_pal}}, _entries_barrier_4_io_y_pal, _entries_barrier_3_io_y_pal, _entries_barrier_2_io_y_pal, _entries_barrier_1_io_y_pal, _entries_barrier_io_y_pal} | c_array) : 7'h0) | (_cmd_write_T_12 | _cmd_write_T_13 | _cmd_write_T_14 | _cmd_write_T_15 | _cmd_write_T_16 ? ~({{2{newEntry_paa}}, _entries_barrier_4_io_y_paa, _entries_barrier_3_io_y_paa, _entries_barrier_2_io_y_paa, _entries_barrier_1_io_y_paa, _entries_barrier_io_y_paa} | c_array) : 7'h0)) & hits);	// @[Bitwise.scala:77:12, Cat.scala:33:92, TLB.scala:415:19, :422:70, :520:{89,104}, :522:87, :535:39, :536:39, :537:39, :564:41, :568:35, :573:37, :579:{8,35,37}, :580:{8,26}, :581:{8,26,53}, :582:{8,29}, :587:19, :633:{33,41}, package.scala:16:47, :73:59, :259:25]
  assign io_ptw_req_valid = _T_22;	// @[package.scala:16:47]
  assign io_ptw_req_bits_bits_addr = r_refill_tag;	// @[TLB.scala:343:25]
  assign io_ptw_req_bits_bits_need_gpa = r_need_gpa;	// @[TLB.scala:350:23]
  assign io_ptw_req_bits_bits_vstage1 = r_vstage1_en;	// @[TLB.scala:348:25]
  assign io_ptw_req_bits_bits_stage2 = r_stage2_en;	// @[TLB.scala:349:24]
endmodule

